### ISSUE TITLE
Consider maintain EFCoreSecondLevelCacheInterceptor.Redis separately?

### ISSUE THREAD

**Issue by hmqgg** [VahidN/EFCoreSecondLevelCacheInterceptor#1]
# Summary of the issue
Now the package depends on Redis related packages such as `Microsoft.Extensions.Caching.StackExchangeRedis`, how about keep different provider implementations separately?

## Environment

```
.NET Core SDK version: 3.1.100
Microsoft.EntityFrameworkCore version: 3.1.1
EFCoreSecondLevelCacheInterceptor version: 1.0.0
```

## Example code/Steps to reproduce:

```
dotnet add package EFCoreSecondLevelCacheInterceptor
```

## Output:

```
Restoring Microsoft.Extensions.Caching.StackExchangeRedis
```

**Comment by VahidN** [comment]
- I added it as a built-in feature, because the Redis cache is the first thing that will be asked.
- Also Let's see how many thumbs up will get your request.

**Comment by VahidN** [comment]
It's a tiny project and I have no plan to do that.

**Comment by VahidN** [comment]
This dependency has been removed. Please use the `CacheManager.Core` provider for it.
