### ISSUE TITLE
Set Global Settings For Cacheable Extension (Not CacheAllQueries)

### ISSUE THREAD

**Issue by fericode** [VahidN/EFCoreSecondLevelCacheInterceptor#10]
# Issue
How to set global settings for `.Cacheable()` instead of writing `.Cacheable(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(5))` for every query we want to cache using default settings? Something like options available for `CacheAllQueries` method.

And what is the default expiration options for `.Cacheable()` anyway?
`

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/df3efcd2d8c947f8781c69c1b5167b7236fff889
