### ISSUE TITLE
Add support for skipping caching of tables/types

### ISSUE THREAD

**Issue by ahmad-kemsan** [VahidN/EFCoreSecondLevelCacheInterceptor#109]
Hi,

We currently have around 40 tables in our database, and we want to skip caching of 3 tables. The current solution requires us to provide the names of 37 tables. 

It would be useful to add a function like SkipCachingContainingTableNames() or SkipCachingContainingTypes()

**Comment by VahidN** [comment]
You can use [SkipCachingCommands](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.AspNetCoreSample/Startup.cs#L40) method for it:
```C#
.SkipCachingCommands(commandText =>
                                // How to skip caching specific commands
                                commandText.Contains("my_real_table_name_1_here", StringComparison.InvariantCultureIgnoreCase) ||
                                commandText.Contains("my_real_table_name_2_here", StringComparison.InvariantCultureIgnoreCase) ||
                                commandText.Contains("my_real_table_name_3_here", StringComparison.InvariantCultureIgnoreCase) 
)
```

**Comment by ahmad-kemsan** [comment]
This solution will also prevent caching of tables where the skip table is a foreign key.

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/a17f61c8d86a43a7e040e880f117054a8b435fb6
