### ISSUE TITLE
Find/FindAsync not supported - Cacheable().FindAsync or Cacheable().Find does not compile

### ISSUE THREAD

**Issue by rbt-eugene** [VahidN/EFCoreSecondLevelCacheInterceptor#11]
# Summary of the issue
Cacheable().FindAsync gives a compilation error as below:

CS1061	'IQueryable<User>' does not contain a definition for 'FindAsync' and no accessible extension method 'FindAsync' accepting a first argument of type 'IQueryable<User>' could be found (are you missing a using directive or an assembly reference?)	AIMunshi API Data	....\User.cs	

SingeOrDefaultAsync, FirstOrDefaultAsync, etc... works

## Environment

```
.NET Core SDK version:  3.1.3
Microsoft.EntityFrameworkCore version: 3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.31
```

## Example code/Steps to reproduce:

```
await context.Users.FindAsync(userId); // this is ok

await context.Users.Cacheable().FindAsync(userId); // does not compile
```
## Output:

```
Exception message:
CS1061	'IQueryable<User>' does not contain a definition for 'FindAsync' and no accessible extension method 'FindAsync' accepting a first argument of type 'IQueryable<User>' could be found (are you missing a using directive or an assembly reference?)	AIMunshi API Data	....\User.cs	

Full Stack trace:
```

**Comment by VahidN** [comment]
[It's reported here](https://github.com/dotnet/efcore/issues/19824).

**Comment by rbt-eugene** [comment]
Thanks, using FirstOrDefault or SingleOrDefault as a workaround.
