### ISSUE TITLE
InvalidCastException: DateTime -> DateTimeOffset

### ISSUE THREAD

**Issue by Vaiune** [VahidN/EFCoreSecondLevelCacheInterceptor#12]
# Summary of the issue
Using PostgreSql with .Net Core 3.1. My entities use DateTimeOffset but after switching to this library from archived one, casting doesn't work.

## Environment

```
.NET Core SDK version: 3.1.3 
Microsoft.EntityFrameworkCore version: 3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.3.1 
```

## Example code/Steps to reproduce:

```
same as your readme
```

## Output:

```
An exception occurred while iterating over the results of a query for context type 'ApplicationDbContext'.
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.
   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Comment by adisazhar123** [comment]
A similar error is happening using Pomelo Mysql:
`An unhandled exception has occurred while executing the request.
System.InvalidCastException: Unable to cast object of type 'System.UInt64' to type 'System.Boolean'.`

**Comment by VahidN** [comment]
@adisazhar123
How did you define that property? I can't reproduce it. [Here is a sample](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12MySQL) with all of the possible property types which works fine with the Pomelo Mysql.

@Vaiune 
`DateTimeOffset` type is designed for Microsoft's SQL Server. Other DB's don't support it natively and [you should write a converter for it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12PostgreSql/DataLayer/ApplicationDbContext.cs#L40).

**Comment by VahidN** [comment]
@adisazhar123 
Added it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/89324c69d7f767aa74348745243d46b96f4f38c0

**Comment by adisazhar123** [comment]
@VahidN woah man, what a quick fix! It's working now. Much appreciated buddy. 😊

**Comment by phs92** [comment]
> @adisazhar123
> How did you define that property? I can't reproduce it. [Here is a sample](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12MySQL) with all of the possible property types which works fine with the Pomelo Mysql.
> 
> @Vaiune
> `DateTimeOffset` type is designed for Microsoft's SQL Server. [Other DB's don't support it natively](https://github.com/npgsql/efcore.pg/issues/473) and [you should write a converter for it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12PostgreSql/DataLayer/ApplicationDbContext.cs#L40).

@VahidN The converter solved my problem. Thank you
