### ISSUE TITLE
Cache invalidation cannot work when using with EasyCaching InMemory Provider and not zero MaxRdSecond

### ISSUE THREAD

**Issue by GeorgeTsaplin** [VahidN/EFCoreSecondLevelCacheInterceptor#122]
# Summary of the issue

When using EasyCaching InMemory config option MaxRdSecond may be situation then Root cache item expires before associated DBCommand row(s) and cache invalidation will not work.
As a result EFCoreSecondLevelCacheInterceptor will return wrong value from cache instead of executing DB request.

## Environment

```
.NET (Core) SDK version: 
EFCoreSecondLevelCacheInterceptor version: 2.4.1
Database: no matter
Cache provider: EasyCaching + InMemory with non zero MaxRdSecond
```

## Example code/Steps to reproduce:

```
//Startup.cs
services.AddEasyCaching(opts =>
{
   opts.UseInMemory(
      config =>
      {
         config.MaxRdSecond = 60;
         ...
      }
}
```

1. query missing item from DB context from Table A with Cacheable();
2. execute Insert command with item from step 1;
3. repeat step 1

## Expected result:

Must be returned item.

## Actual result:

Returned NULL value from cache

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/21badfab832a64614c46fee3d3da68bcba083e78

**Comment by GeorgeTsaplin** [comment]
I think real problem is in caching library, there should be posibility to add dependend items with equal time to live value.
