### ISSUE TITLE
How to avoid EF logging CommandExecuted when cache was used

### ISSUE THREAD

**Issue by billybraga** [VahidN/EFCoreSecondLevelCacheInterceptor#124]
Not really an issue, but I'd like to stop EF from logging CommandExecuted when the query cache result was returned.

Or maybe I could filter out EF Core's CommandExecuted logs and log my own in an interceptor, but I have no way of knowing when a scalar result was returned from cache (for readers I could check if the reader is EFTableRowsDataReader, but even that seems shady).

Any ideas?

**Comment by VahidN** [comment]
You can always write [your own Logger](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/DebugLoggerProvider.cs#L9) and [use it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/172e1e76a83017f78c2fcdf1b5c533b057873888/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L124).

**Comment by billybraga** [comment]
Yes, but this won't allow me to log the real db queries.

**Comment by VahidN** [comment]
- Put a break-point on the Log method to see what's going on (it has every thing).
- [Or use a custom filter](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#custom-filters)
```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .LogTo(
            Console.WriteLine,
            (eventId, logLevel) => logLevel >= LogLevel.Debug
                                   || eventId == CacheableEventId.CacheHit
                                   || eventId == CacheableEventId.QueryResultCached);
```

**Comment by billybraga** [comment]
This will allow me to log EFCoreSecondLevelCacheInterceptor logs, but not tell me how much time real db queries take. QueryResultCached logs doesn't contain the db query duration.
