### ISSUE TITLE
EF Core 6 support?

### ISSUE THREAD

**Issue by joelmandell** [VahidN/EFCoreSecondLevelCacheInterceptor#125]
# Summary of the issue
Hi :)
I wonder how the timeline for supporting ef core 6, looks like?
Thanks for a great interceptor!

## Environment

```
.NET (Core) SDK version: 5.x
Microsoft.EntityFrameworkCore version: 6.x
EFCoreSecondLevelCacheInterceptor version: 2.8.0
Database: MSSQL
Cache provider: Redis
```

**Comment by VahidN** [comment]
Have you tested it? [It should work](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCoreSecondLevelCacheInterceptor.csproj#L102).

**Comment by joelmandell** [comment]
I get exception when using EF Core 6 Preview.

https://user-images.githubusercontent.com/109020/118355471-75aa6d00-b570-11eb-96e3-76fb49a3a67f.mp4

**Comment by VahidN** [comment]
```
System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
```
This exception can be addressed easily by compiling this library against the new EF-Core 6x binaries. But ... it will break the compatibility with EF-Core 5x.

**Comment by joelmandell** [comment]
Okay, thx. I try to compile it on my own then against ef core 6 :)

**Comment by VahidN** [comment]
[Added initial EF-Core 6x support](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/c47aeef304cfc3c7eadc8bb3d047786bd40fd9de). I'm not going to publish its NuGet package for now (until ef-core 6 is final), because it's not possible to differentiate between ef-core 5x and 6x in libraries.

**Comment by joelmandell** [comment]
Thank you sir! 👌🙏

**Comment by VahidN** [comment]
V 2.9 supports both v5x & 6x in one library.
