### ISSUE TITLE
Entity tracking

### ISSUE THREAD

**Issue by adambajguz** [VahidN/EFCoreSecondLevelCacheInterceptor#126]
I have found that in [EFCachedQueryExtensions](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCachedQueryExtensions.cs) there is an automatically added `AsNoTracking`? Is it really required? What if I want to change entities and then save?

**Comment by VahidN** [comment]
When you are reading an entity from the cache for the second time, it's disconnected form the context. So using `AsNoTracking` reduces the change tracking proxies creation when it's not going to be used at all.

> What if I want to change entities and then save?

[Read the related docs](https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking)
