### ISSUE TITLE
Why just 32-bit xxHash?

### ISSUE THREAD

**Issue by adambajguz** [VahidN/EFCoreSecondLevelCacheInterceptor#127]
Why just 32-bit xxHash? Aren't you concerned about collisions?

Initially I thought that this is just a default that can be changed by adding a custom `EFCacheKeyProvider` but `XxHashUnsafe.ComputeHash` is also used [`EFSqlCommandsProcessor.GetSqlCommandTableNames(string commandText)`](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/99c857f0a84ec14e18f5c400655c85eda6dcc270/src/EFCoreSecondLevelCacheInterceptor/EFSqlCommandsProcessor.cs#L79), so also a custom `EFSqlCommandsProcessor` is required.

**Comment by VahidN** [comment]
> Aren't you concerned about collisions?

No. I'm not. This is a very fast and reliable hashing algo and I'm using it for years without any issues.
