### ISSUE TITLE
StringExtensions interferes with native methods/extensions

### ISSUE THREAD

**Issue by NinjaCross** [VahidN/EFCoreSecondLevelCacheInterceptor#134]
# Summary of the issue

The class **StringExtensions** is public, and due to this, its methods are visible externally, and used by the compiler **instead** of the native/existing ones in the environment when running under netcoreapp3.1

Please make the class **StringExtensions** internal, so its methods are not mistakenly used by caller code.

I would suggest to apply the same criteria to any other class in the library that is not needed to be visible externally 

## Environment

```
.NET (Core) SDK version: netcoreapp3.1
EFCoreSecondLevelCacheInterceptor version: any version containing the class StringExtensions 
```

**Comment by VahidN** [comment]
Changed it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/fc185d8a2e283a64f4fb2b807222d2c8ea859372
