### ISSUE TITLE
Support multi-targeted libraries by decoupling .Net and EF Core versions

### ISSUE THREAD

**Issue by jvincent-siplay** [VahidN/EFCoreSecondLevelCacheInterceptor#135]
# Summary of the issue
I'm having trouble integrating this library with a multi-targeted EF Core project.

My EF Core 3.1 code is in a data access class library that is configured with multiple target frameworks:
`<TargetFrameworks>net5.0;netstandard2.0;net471;</TargetFrameworks>`

That library is used by 3 different projects: a .Net 4.7 web application, a .Net Core 2.1 WebAPI (compatible with .Net Standard 2.0), and a .Net 5 console application.

This has been working fine and now I want to add caching, but it seems that the .Net version and EF Core version are tightly coupled in EFCoreSecondLevelCacheInterceptor.  I have read the explanations in the previous issues [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/56) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/52) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/50), but I still believe that is not 100% correct.

EFCoreSecondLevelCacheInterceptor sees the `net5.0` target and is forcing my class library to use EF Core 5.  While it's true that EF Core 5 requires .Net 5, the reverse is not true.  It says [here](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/#what-you-should-target):
>  .NET 5 and all future versions will continue to support .NET Standard 2.1 _**and earlier**_.  (emphasis mine)

This means that .Net 5 applications are still compatible with .Net Standard 2.0, and therefore work with EF Core 3.1 as well.  .Net 5 (and future) versions should not be coupled to specific versions of EF Core libraries.

(Side note: if you're wondering _why_ this is needed, it's part of the migration path to .Net 5.  Eventually everything will be on the same version, but things get messy along the way.  This is [supported by the EF Core team](https://github.com/dotnet/efcore/issues/23223#issuecomment-723418557).)

## Environment

```
.NET (Core) SDK version:  net5.0;netstandard2.0;net471;
Microsoft.EntityFrameworkCore version: 3.1.11
EFCoreSecondLevelCacheInterceptor version: 3.0.0
Database: MySQL
Cache provider: Redis
```

## Example code/Steps to reproduce:

Create a multi-target class library:
**Data.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
    [...]
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EasyCaching.Redis" Version="1.1.0" />
    <PackageReference Include="EFCoreSecondLevelCacheInterceptor" Version="3.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.4" />
    [...]
  </ItemGroup>
</Project>
```

Create two applications that reference that class library:

**Net5App.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
  </ItemGroup>
</Project>
```

**NetCoreApp.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
  </ItemGroup>
</Project>
```

## Output:

Build error:
```
Error	NU1107	Version conflict detected for Microsoft.EntityFrameworkCore.Relational. Install/reference Microsoft.EntityFrameworkCore.Relational 5.0.0 directly to project Data to resolve this issue. 
 Data -> EFCoreSecondLevelCacheInterceptor 3.0.0 -> Microsoft.EntityFrameworkCore.Relational (>= 5.0.0)
 Data -> Pomelo.EntityFrameworkCore.MySql 3.2.4 -> Microsoft.EntityFrameworkCore.Relational (>= 3.1.8 && < 5.0.0).
```

**Comment by VahidN** [comment]
This library [does support multiple target frameworks](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCoreSecondLevelCacheInterceptor.csproj#L6).

> .Net 5 applications are still compatible with .Net Standard 2.0

No. .NET 5, is .NET 5. The last version of .Net Standard `was` 2.1 and now It's just 5 and nothing else. .Net Standard is dead for good.

> .NET 5 and all future versions will continue to support .NET Standard 2.1 and earlier

This means you can use the older libraries with .NET 5 apps and not the opposite!

EF-Core is bound to specific .NET and .NET core versions and it's respected in this library. [Open its NuGet page](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/), select an specific version of it and then look at its base framework (dependencies). You should use an specific version of it for different frameworks.


Pomelo.EntityFrameworkCore.MySql `3.2.4` [is compiled for EF-Core 3x `only`](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.2.4). You can't use it freely. It muse be bound to an specific version [this way](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCoreSecondLevelCacheInterceptor.csproj#L81).

**Comment by jvincent-siplay** [comment]
Thank you for the reply, apologies if my wording was confusing.   I am _not_ trying to use EF Core 5 with an older framework, I know that will not work.  I am using an older library (EF Core 3.1) with a .Net 5 app as you say, and indeed my applications have been working fine for months until I tried to add EFCoreSecondLevelCacheInterceptor. 

I suspect that [this](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCoreSecondLevelCacheInterceptor.csproj#L111-L113) is the problem, it seems that it should read like this instead:

```
  <ItemGroup Condition="('$(TargetFramework)' == 'net5.0')">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="[3.1,)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="[3.1,)" />
```

It's true that EF Core 3.1 has a framework dependency on .Net Standard 2.0, but EF Core 3.1 is still compatible with .Net 5 applications, and should be allowed.  The way the condition is currently written prevents the transitive dependency from working correctly.

**Comment by VahidN** [comment]
This library is not limiting you, Pomelo.EntityFrameworkCore.MySql 3.2.4 [is restricting](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.2.4) the usage of EF-Core:
```
 Microsoft.EntityFrameworkCore.Relational (>= 3.1.8 && < 5.0.0) 
```

**Comment by jvincent-siplay** [comment]
I'm using EF Core 3.1.11, which falls within that range.

**Comment by VahidN** [comment]
Your posted error message means you are not limiting the boundaries of EF-Core correctly as I mentioned. If you don't bound it, the last version will be used.

**Comment by jvincent-siplay** [comment]
Ok, I have tried your suggestion.  I added the boundaries to try to force it to use EF Core 3.1.11:
```
  <ItemGroup Condition=" ('$(TargetFramework)' == 'net5.0')">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="[3.1.11,4)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="[3.1.11,4)" />
  </ItemGroup>
```

Now I'm getting a different error:
```
Error	NU1605	Detected package downgrade: Microsoft.EntityFrameworkCore from 5.0.0 to 3.1.11. Reference the package directly from the project to select a different version. 
 Net5App -> Data -> EFCoreSecondLevelCacheInterceptor 3.0.0 -> Microsoft.EntityFrameworkCore (>= 5.0.0) 
 Net5App -> Microsoft.EntityFrameworkCore (>= 3.1.11 && < 4.0.0)
```
It looks like EFCoreSecondLevelCacheInterceptor is trying to force me to use EF Core 5 even when I limit the boundaries.

I have tried adding EF Core 3.1.11 directly to the Net5App project as suggested in the error (instead of pulling it in as a transitive dependency via the Data project) but it has the same error.

I've created a minimal [sample project](https://github.com/jvincent-siplay/EFCacheError) to reproduce the issue (using SqlServer instead of Pomelo.)  If you remove the cache interceptor package on [this line](https://github.com/jvincent-siplay/EFCacheError/blob/master/Data/Data.csproj#L8) then it compiles.

**Comment by VahidN** [comment]
I can't change the lower bound of EF-Core 5x here (I can't use Version="[3.1,)" for it), because `they` have changed the signature of `DbCommandInterceptor` in EF-Core 5x and it's not compatible with EF-Core 3x anymore. They used `Task<int>` in v3x and now they are using `ValueTask`s.

**Comment by VahidN** [comment]
Suppose you want to create a new .NET 5x based library and you want to use the EF-Core in it and also you want to support EF-Core 3x and EF-Core 5x at the same time in your library. Can you do that?
The answer is "no"! Because it's not possible to differentiate between different piece of your code based on the different versions of EF-Core (a given dependency). Compiler directives (#if/#else) can only be created based on the specific target frameworks (.NET5 here) and not based on the different versions of the specific dependency and … EF-Core 3x and 5x are not compatible at all. The old one uses `Task` based methods and the second one loves `ValueTask`s and uses it everywhere. Now our interceptor should support both `Task` based methods for EF-Core 3x and at the same time `ValueTask`s based methods for the EF-Core 5x code. Is it possible? No. Because compiler directives don't support such a scenario. I can't say #If `EF-Core5x` Then use `ValueTask`s. I have to say #If `NET5` Then use only this specific dependency and I can't define a range of versions (select EF-Core>=3.1 for .NET5) here because again this range doesn't mean having a consistent and completely compatible libraries in it.
But … I can create lots of different `EFCoreSecondLevelCacheInterceptor` binaries with names such as `EFCoreSecondLevelCacheInterceptor-for-NET5-and-EFCore5x` or `EFCoreSecondLevelCacheInterceptor-for-NET5-and-EFCore3x` and so on for every and each available target framework and … this is not logical.

**Comment by jvincent-siplay** [comment]
Thank you for the detailed explanation, I think I understand the problem much better now.  My only other thought was to use reflection to determine the EF Core package version, but it sounds like maybe that can't be done at runtime because that interceptor signature has changed.

I will try to restructure my projects to work around these issues, thanks for taking the time to explain the problems.  This package looks awesome and I'm excited to get it working in my project!
