### ISSUE TITLE
Unable to cast object of type 'System.Guid' to type 'System.String'

### ISSUE THREAD

**Issue by al-wys** [VahidN/EFCoreSecondLevelCacheInterceptor#137]
I got an error from the below line while querying a table which primary key is a GUID. In the database, it's char(36).

https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/fc185d8a2e283a64f4fb2b807222d2c8ea859372/src/EFCoreSecondLevelCacheInterceptor/EFTableRowsDataReader.cs#L426

![image](https://user-images.githubusercontent.com/16317690/125225923-a99cd700-e302-11eb-9587-fcfc1a8587d5.png)

Any advise? Thanks.

**Comment by al-wys** [comment]
BTW, I'm using 3.1.1 version.

**Comment by VahidN** [comment]
What's your setup? database, serializers, etc.

**Comment by al-wys** [comment]
My database is MySql, the EF provider is MySql.EntityFrameworkCore.

And here is the model's properties:
```csharp
public Guid Id { get; set; }
public string Name { get; set; }
public string SystemId { get; set; }
public string Email { get; set; }
public VendorType VendorType { get; set; } // VendorType is an enum
```

Here is the entity builder:
```csharp
builder.Property(x => x.Id)
  .HasColumnType("char(36)");

builder.HasKey(x => x.Id)
  .HasName("PRIMARY");

builder.Property(x => x.SystemId)
  .HasColumnType("varchar(36)");

builder.Property(x => x.Email)
  .HasColumnType("varchar(200)");

builder.Property(x => x.VendorType)
  .HasColumnName(nameof(Vendor.VendorType) + "Id")
  .HasConversion<short>();
```

**Comment by VahidN** [comment]
I have [a MySQL sample here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12MySQL). It uses [a Guid field](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12MySQL/Entities/Person.cs#L32). But it's using [the memory-cache-provider](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12MySQL/EFServiceProvider.cs#L59). Do you have the same setup? Are you using a memory-cache provider or Redis provider and what's their settings?

**Comment by al-wys** [comment]
Yeah, same with you, I'm using the default memory cache provider. Let me check the sample, thanks.

**Comment by al-wys** [comment]
> I have [a MySQL sample here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12MySQL). It uses [a Guid field](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12MySQL/Entities/Person.cs#L32). But it's using [the memory-cache-provider](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue12MySQL/EFServiceProvider.cs#L59). Do you have the same setup? Are you using a memory-cache provider or Redis provider and what are their settings?

Yeah, same with you, I'm using the default memory cache provider. Let me check the sample, thanks.

**Comment by VahidN** [comment]
Fixed it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/63e5fb9f72b71185712b7f44bfdea4b88369230d
