### ISSUE TITLE
Cache Invalidation

### ISSUE THREAD

**Issue by c5racing** [VahidN/EFCoreSecondLevelCacheInterceptor#139]
# Summary of the issue
How is the cache key determined for invalidation?  Is it by DBContext, connection string or other?  We have multiple customers on the multi tenant platform and only want to invalidate as necessary per customer when changes happen, not for all customers

## Environment

```
.NET (Core) SDK version: 
Microsoft.EntityFrameworkCore version: 
EFCoreSecondLevelCacheInterceptor version: 
Database: (e.g. SQL Server, SQLite, etc.)
Cache provider: (e.g. in-memory, redis, etc.)
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by SavoInfostream** [comment]
In the scenario where I am caching an entire table, will, after an update of a single record, entire cache of that table be invalidated or just that single record?

**Comment by VahidN** [comment]
The entire cache of that table.
