### ISSUE TITLE
 CacheDependencies: EFUnknownsCacheDependency

### ISSUE THREAD

**Issue by 2693252993** [VahidN/EFCoreSecondLevelCacheInterceptor#14]
# Summary of the issue
Hello ,I use  Pomelo.EntityFrameworkCore.MySql

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version:3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.3.1
```

## Example code/Steps to reproduce:

```
paste your core code
```

![image](https://user-images.githubusercontent.com/27254047/77906654-dfa77a80-72ba-11ea-890d-331bfeba6684.png)

then code 
_insideSquareBracketsOrQuotes.Matches(sql)

can't matche any tableName

![image](https://user-images.githubusercontent.com/27254047/77907087-a02d5e00-72bb-11ea-9906-513ba6c870f9.png)
![image](https://user-images.githubusercontent.com/27254047/77907153-b9360f00-72bb-11ea-99fa-0e6e927844a4.png)

## Output:
info: EFCoreSecondLevelCacheInterceptor.EFCacheDependenciesProcessor[0]
      It's not possible to calculate the related table names of the current query[SELECT EXISTS (
          SELECT 1
          FROM `Navigation` AS `n`
          WHERE (`n`.`Deleted` = FALSE) AND ((LOWER(`n`.`ItemUrl`) = @__ToLower_0) AND `n`.`IsList`))]. Please use EFCachePolicy.Configure(options => options.CacheDependencies("real_table_name_1", "real_table_name_2")) to specify them explicitly.
info: EFCoreSecondLevelCacheInterceptor.EFCacheDependenciesProcessor[0]
      ContextTableNames: Api_Route, Content, Department, Log, Menu, Menu_Auth_Mapping, Navigation, News, News_Type, Position, Request_Log, Role, Role_Api_Route_Mapping, Role_User_Mapping, Role_Web_Route_Mapping, Tenement, User_Department_Mapping, User_Info, User_Position_Mapping, Web_Route, PossibleQueryTableNames:  -> CacheDependencies: EFUnknownsCacheDependency.
```
Exception message:
Full Stack trace:
```

**Comment by 2693252993** [comment]
I changed the regex
@"(?:FROM|JOIN|INTO|UPDATE)\s[\[""`](.*?)[\]""`]\s*
can work

**Comment by VahidN** [comment]
Thanks. Added it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/2cb746d2f4a8b220ea9d346b19928033fda42268
