### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.

### ISSUE THREAD

**Issue by NinjaCross** [VahidN/EFCoreSecondLevelCacheInterceptor#140]
# Summary of the issue

While retrieving values stored into the cache, we are getting the mentioned exception.

System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.

## Environment

```
.NET (Core) SDK version:  5
Microsoft.EntityFrameworkCore version: 5.0.12
EFCoreSecondLevelCacheInterceptor version:  2.3.1
Database: (e.g. SQL Server, SQLite, etc.): Sql Server
Cache provider: (e.g. in-memory, redis, etc.): InMemory
```

## Output:

The full stacktrace is

Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'TeamSystem.Enterprise.Hub.Entities.TeamSystemEntitiesDbContext'.
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetString(Int32 ordinal) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFTableRowsDataReader.cs:line 426
   at lambda_method215(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

**Comment by VahidN** [comment]
V 2.3.1? Please try the last version [which is 3.2.0](https://www.nuget.org/packages/EFCoreSecondLevelCacheInterceptor/#versions-tab)

**Comment by NinjaCross** [comment]
> V 2.3.1? Please try the last version [which is 3.2.0](https://www.nuget.org/packages/EFCoreSecondLevelCacheInterceptor/#versions-tab)

Unfortunately I cannot upgrade the package due to project constraints.
Anyway, I solved the problem.
I discovered that the exception was caused by adding the option `<Nullable>enable</Nullable>` to my project.
This somehow changed the interaction between the EF and the EFCoreSecondLevelCacheInterceptor.
Removing the `<Nullable>enable</Nullable>` option solved the problem.

The root problem was the following.
Enabling that option, my datamodel became incongruent with the real database structure.
In my table, some string columns are nullable.
In my datamodel, the string properties are *not* explicitly declared as nullable.
This didn't cause compilation errors, of course, and apparently the query results were correctly stored into the cache.
The problem arised when retrieving values from the cache.
Apparently, _retrieving_ (from the cache) a _previously stored_ (column) NULL value, will raise the exception if the corresponding property in the entity datamodel is not itself decorated as "nullable" (i.e. `string?` instead of `string`).

This is somehow "right-ish", because the NULL value is not coherent with the property type of the datamodel, but I'm a bit perplexed by the fact that the exception is raised only when retrieving the value, and not when storing it into the cache.
This makes it very difficult to debug problems like this.

Do you have any recommendation for this scenario (apart from the obvious "check your datamodel consistency against the database" :D ) ?
Is it more "graciously handled" in 3.x versions ?

**Comment by VahidN** [comment]
`DBNull` will be checked in V 3.2.1 as well.
