### ISSUE TITLE
Multi-Tenant Caching

### ISSUE THREAD

**Issue by c5racing** [VahidN/EFCoreSecondLevelCacheInterceptor#141]
# Summary of the issue
In reviewing the cache key in https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/139, I don't see a way to setup caching per Tenant on a multi-tenant application.  Currently I configure my connection string per tenant in the OnConfiguring of my context by injecting a configuration interface to determine the correct database/connection string.  Is there any way to make the cachekey tenant independant?

```
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseNpgsql(_configuration.GetValue<string>("DbContextConnectionString"));
                optionsBuilder.AddInterceptors(_serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>());
            }
        }
```

**Comment by VahidN** [comment]
Tenant independent or dependent? I can change the [getCacheKey](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L76) method to consider/add the `command.Connection.ConnectionString` to the list of its builder, if you want.

**Comment by c5racing** [comment]
> Tenant independent or dependent? I can change the [getCacheKey](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L76) method to consider/add the `command.Connection.ConnectionString` to the list of its builder, if you want.

Adding the ConnectionString to the cachekey would do the trick.  Thank you for the consideration.

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/5b454f14cfb0070e57a2b602a7d19f382186b91c
