### ISSUE TITLE
Partial cache invalidation using table names and SqlTableDependency

### ISSUE THREAD

**Issue by letherman255** [VahidN/EFCoreSecondLevelCacheInterceptor#144]
# Summary of the issue

Is it possible to use the `IEFCacheServiceProvider` to invalidate caching of specific tables ?

Some tables in my database are modified using SQL Server transactional replication from another database and not though EF. The cache is therefore not automatically invalidated. The application is notified of a change on those tables using `SqlTableDependency` (Which results in an event being fired when a change occurs on a table which contains the new and old entity).  Clearing the whole cache works quite well but is definately not the most efficient way to go. I also don't want to simply disable caching for those tables as those are among the most frequently accessed ones in the project which is why I needed caching in the first place.

it would even be better if I could invalidate the specific entities that have changed but this seems even harder.
## Environment

```
.NET (Core) SDK version: net5.0
Microsoft.EntityFrameworkCore version: 5.0.12
EFCoreSecondLevelCacheInterceptor version: 3.2.3
Database: SQL Server 2019
Cache provider: EasyCaching.Redis 1.4.1
```

## Example code/Steps to reproduce:

This works fine but is not really efficient.
```
        private void HandleOnChanged(object sender, RecordChangedEventArgs<BusinessPartnerDto> e)
        {
            _logger.LogWarning("Business partner changed {0}", e.Entity.CardName);
            _cacheServiceProvider.ClearAllCachedEntries(););
        }
```
This throws an System.ArgumentNullException on 'cacheKey')
```
private void HandleOnChanged(object sender, RecordChangedEventArgs<BusinessPartnerDto> e)
        {
            _logger.LogWarning("Business partner changed {0}", e.Entity.CardName);
            EFCacheKey efCacheKey = new EFCacheKey(new HashSet<string>() { "OCRD" });
            _cacheServiceProvider.InvalidateCacheDependencies(efCacheKey);
        }
```
I am aware that this is probably not the way to do it but I can't find any better.

## Output:

```
Exception message:
Full Stack trace:
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'cacheKey')
  Source=EasyCaching.Core
  StackTrace:
   at EasyCaching.Core.ArgumentCheck.NotNullOrWhiteSpace(String argument, String argumentName)
   at EasyCaching.Redis.DefaultRedisCachingProvider.BaseGet[T](String cacheKey)
   at EasyCaching.Core.EasyCachingAbstractProvider.Get[T](String cacheKey)
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.<>c__DisplayClass8_0.<InvalidateCacheDependencies>b__0() in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 131
   at EFCoreSecondLevelCacheInterceptor.ReaderWriterLockProvider.TryWriteLocked(Action action, Int32 timeout) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\ReaderWriterLockProvider.cs:line 81
   at EFCoreSecondLevelCacheInterceptor.EFEasyCachingCoreProvider.InvalidateCacheDependencies(EFCacheKey cacheKey) in D:\Prog\1398\EFCoreSecondLevelCacheInterceptor\src\EFCoreSecondLevelCacheInterceptor\EFEasyCachingCoreProvider.cs:line 145
   at API.Cache.CacheInvalidationService.HandleOnChanged(Object sender, RecordChangedEventArgs`1 e) in D:\ASC-2\ASC2\API\Cache\CacheInvalidationService.cs:line 46

  This exception was originally thrown at this call stack:
    [External Code]
    API.Cache.CacheInvalidationService.HandleOnChanged(object, TableDependency.SqlClient.Base.EventArgs.RecordChangedEventArgs<DataAccess.Models.BusinessPartnerDto>) in CacheInvalidati
```

Thanks for your help.

**Comment by VahidN** [comment]
Use it this way to specify the root cache keys which are a collection of a Prefix+TableName:
```C#
_cacheServiceProvider.InvalidateCacheDependencies(new EFCacheKey(new HashSet<string>() 
{
   "EF_TableName1", // "EF_" is the cache key's prefix
   "EF_TableName2" 
} {  KeyHash = "empty" }));
```

**Comment by letherman255** [comment]
This worked like a charm 😄 ! I noticed that I forgot about the cache key prefix.

```
_cacheServiceProvider.InvalidateCacheDependencies(new EFCacheKey(new HashSet<string>()
{
    "EF_OCRD",
}){ KeyHash = "empty" });
```
Thanks for your help.

**Comment by strigefleur** [comment]
@VahidN what's going to happen when there are multiple tables with same name but different table schemas?

Is it safe to assume that interceptor correctly handles the case where there `databaseName.schema1.myTable` and `databaseName.schema2.myTable` both coexist?

What is the way of specifying the `EFCacheKey` in that case?

**Comment by VahidN** [comment]
This library doesn't care about the table schemas. Caches of all of the tables with similar names will be invalidated.
