### ISSUE TITLE
Use with .net framework 4.7

### ISSUE THREAD

**Issue by eustma** [VahidN/EFCoreSecondLevelCacheInterceptor#146]
# Summary of the issue

I would like to use the library with asp.net mvc .net framework 4.7 and with EntityFramework Core 3.1.
I can see that it is compatible with these versions.
Would you have any configuration example for this one?

## Environment

```
.NET Framework SDK version: 4.7
Microsoft.EntityFrameworkCore version: 3.1
EFCoreSecondLevelCacheInterceptor version: 3.2.3
```

**Comment by VahidN** [comment]
[You should create your own service provider and use it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue9SQLiteInt32/EFServiceProvider.cs).

**Comment by eustma** [comment]
Please. could you tell me how to use it, in an asp.net mvc application?
We use Ninject as DI.
Thanks a lot.
