### ISSUE TITLE
EntityFramework Core for .Net 5 in Console

### ISSUE THREAD

**Issue by flo2000ace** [VahidN/EFCoreSecondLevelCacheInterceptor#148]
Hi,

i looked at your project and i am interested using it, but i cant find any samples on your sample page, except for one with Consoles. So i wanted to ask how difficult it is to use this libary for Redis Caching in a Console Application? Am i need a service to use this libary, e.g. at the asp.net samples it looks like that. Also on the one Console Sample there is also a Service, but i dont understand, ef core also works without a service?

Yours,
Florian

**Comment by VahidN** [comment]
[Follow this sample](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue123WithMessagePack/EFServiceProvider.cs).
