### ISSUE TITLE
Updated Config to use Redis for Backplane only

### ISSUE THREAD

**Issue by jasenf** [VahidN/EFCoreSecondLevelCacheInterceptor#15]
Hi there, this is a great update!  However, it broke our configuration that we had for using an in-memory but Redis as a backplane to coordinate invalidation across servers.

Can you provide an updates configuration sample for doing this?  Maybe even a template project?

**Comment by jasenf** [comment]
Upon further digging it looks like you have changed the way you track dependencies.  You are now using a concurrent local dictionary instead of the memory cache, which basically makes this impossible.  Is there any chance we could go back to using the memorycache for change tracking?

**Comment by VahidN** [comment]
That `ConcurrentDictionary` is used to store the table names of the current context. This information is usually constant. CacheDependencies will be calculated per each commandText and its result will be stored in the selected cache (in-memory or redis).

**Comment by jasenf** [comment]
That's too bad.  Your previous library used MemoryCache to store invalidation, instead of an ConcurrentDictionary, which worked beautifully with CacheManager  -- It allowed us to bind your library  to  MemoryCache and CacheManager to Redis as a backplane to keep all our servers in synch via invalidation.  It allworked really really nice.

I hope you change your mind.  Removing cross-server synchronization is a major feature removal from the previous version.

**Comment by VahidN** [comment]
Added CacheManager.Core support via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/cf74945ab54a0aadd984012bd0a4272c6980a292
