### ISSUE TITLE
System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application.

### ISSUE THREAD

**Issue by mischa71lab** [VahidN/EFCoreSecondLevelCacheInterceptor#151]
# Summary of the issue

System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.

BinaryFormatter is obsolete in AspNet Core in .net5.0

Workaround:
 <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>

## Environment
.NET (Core) SDK version:  5.0 / 6.0

**Comment by VahidN** [comment]
This library is not using `BinaryFormatter` anymore. Just use the last version of it.

**Comment by mischa71lab** [comment]
i'm using nuget package 3.3.0 with EasyCaching.Redis 1.5.0
All latest versions.

**Comment by VahidN** [comment]
[Follow this topic](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/142)
