### ISSUE TITLE
Setting global cache timeout causes all queries to be cached

### ISSUE THREAD

**Issue by PieterBoeren** [VahidN/EFCoreSecondLevelCacheInterceptor#154]
# Summary of the issue
When setting the global caching options with:

`options.UseMemoryCacheProvider(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(5))`

the library starts caching all queries, so even the ones without `Cacheble()` in the Linq query.

## Environment

```
.NET (Core) SDK version: 6
Microsoft.EntityFrameworkCore version: 6.0.3
EFCoreSecondLevelCacheInterceptor version: 3.3.0
Database: (e.g. SQL Server, SQLite, etc.): PostgreSQL
Cache provider: (e.g. in-memory, redis, etc.): In-Memory
```

## Example code/Steps to reproduce:

```
options.UseMemoryCacheProvider(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(5))
```

## Output:

```
EFCoreSecondLevelCacheInterceptor.EFDebugLogger: Debug: InstanceId: 1bb95965-d986-42e1-9ba4-b1613970d5f2, Started @18-3-2022 13:04:20 UTC. Using EFCachePolicy: EFCachePolicy --> Absolute|00:05:00|||False.

...

EFCoreSecondLevelCacheInterceptor.EFDebugLogger: Debug: InstanceId: 1bb95965-d986-42e1-9ba4-b1613970d5f2, Started @18-3-2022 13:04:20 UTC. TableRows[6941e28c-f9c8-445b-aeca-1695487802c0] added to the cache[KeyHash: EF_9A5853DD07378EF0, CacheDependencies: EF_sometable.].
```

When disabling the standard cache timeout options (`options.UseMemoryCacheProvider()`), I get this output for the very same query:

```
EFCoreSecondLevelCacheInterceptor.EFDebugLogger: Debug: InstanceId: 0dcb4bd9-f9f8-4da2-b5c4-1a6b7ff3d7bd, Started @18-3-2022 13:03:33 UTC. Skipping a none-cachable command ....
```
To be perfectly clear: there isn't any `Cacheable()` in my query, the only change I'm making is the options for the `UseMemoryCacheProvider`, with the above result.

**Comment by PieterBoeren** [comment]
Checked the sources as well, to me, it doesn't seem logical to also set the `CacheAllQueriesOptions` to active when setting the timeout values. Is there any other way to set a global timeout and not enabling caching of all queries?

```C#
/// <summary>
/// Introduces the built-in `EFMemoryCacheServiceProvider` to be used as the CacheProvider.
/// If you specify the `Cacheable()` method options, its setting will override this global setting.
/// </summary>
/// <param name="expirationMode">Defines the expiration mode of the cache items globally.</param>
/// <param name="timeout">The expiration timeout.</param>
public EFCoreSecondLevelCacheOptions UseMemoryCacheProvider(CacheExpirationMode expirationMode, TimeSpan timeout)
{
    Settings.CacheProvider = typeof(EFMemoryCacheServiceProvider);
    Settings.CacheAllQueriesOptions = new CacheAllQueriesOptions
    {
        ExpirationMode = expirationMode,
        Timeout = timeout,
        IsActive = true
    };
    return this;
}
```

**Comment by VahidN** [comment]
You are hiding something.
- How did you get `EFCachePolicy --> Absolute|00:05:00|||False.` when you say there isn't any `Cacheable()` in my query? It comes directly from [the tagging](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCachedQueryExtensions.cs#L32) a query.
- That CacheAllQueriesOptions [is not going](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCachePolicyParser.cs#L222) to be processed when there is no `Cacheable()` method.
- There are [other possible scenarios](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCachePolicyParser.cs#L123-L126) as well which are documented in the readme file.

**Comment by PieterBoeren** [comment]
I sure could have missed something, but can you explain why with only the removal of the default memory cache options, the query is not cached anymore (as per the logging I provided above)?

I do have some `Cacheable()` calls on some queries, but not on all, I wouldn't expect those to be cached...

**Comment by VahidN** [comment]
What's your full startup settings, related to this library?

**Comment by PieterBoeren** [comment]
```
serviceCollection.AddEFSecondLevelCache(options => options
          .UseMemoryCacheProvider(CacheExpirationMode.Absolute, TimeSpan.FromSeconds(cacheTimeoutInSeconds))
          .DisableLogging(value: !enableCacheLogging)
          .UseCacheKeyPrefix($"EF_{tenantIdentifier}")); // Add a prefix per tenant to make sure each tenant gets its own cache


serviceCollection
        .AddDbContext<ITenantDbContext, TenantDbContext>(
          (serviceProvider, optionsBuilder) =>
          {
            optionsBuilder.UseNpgsql(connectionString);

            if (enableCaching)
            {
              _ = optionsBuilder.AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>());
            }
          },
          ServiceLifetime.Transient);

```

**Comment by VahidN** [comment]
Try V 3.4.

**Comment by PieterBoeren** [comment]
Seems to work, thanks! :)
