### ISSUE TITLE
specific invalidation

### ISSUE THREAD

**Issue by Mahloujian** [VahidN/EFCoreSecondLevelCacheInterceptor#156]
hi Dear Vahid,
we have a question:
for example, we have a table called product which is used for 30.000 companies' data. so when the first company cached its products. after a while the second company cache its products, but after a few times, the second one updates one of its product rows that is not related to the first one. so is it possible to invalidate JUST the second company product cache data?

**Comment by VahidN** [comment]
No. All of the related data will be invalidated and also querying and finding these types of issued are very time consuming and doesn't worth it. rebuilding the cache is a lot faster and more accurate.
