### ISSUE TITLE
Cache dependency on entities instead table names

### ISSUE THREAD

**Issue by mamdos** [VahidN/EFCoreSecondLevelCacheInterceptor#157]
# Summary of the issue

Hi Vahid, If I query the whole Table (for example News table) and then update one record in this table is this library deletes all table data from the cache and then queries all the records again?  or just get that single updated record and updates the cache with that?

I don't think we need to query all records to keep the cache fresh for just one record that changed.

I'm struggling with this and I don't know how can I update the cache without a query to all data every time just a single row changes 
please guide me on how can I achieve that.

**Comment by mamdos** [comment]
فارسی کامنت میذارم که منظورمو بهتر برسونم :
با چیزی که از داکیومنت و تستی که کردم فهمیدم این کتابخونه شما میاد بر اساس اسم هر table کش رو track میکنه و هر وقت آپدیتی روی این table ها انجام بشه میاد دوباره کل ریکورد ها رو از دیتابیس میخونه و دوباره کش میکنه 
خب اگر اینطوری باشه کوچک ترین تغییری توی هر ریکورد ما (مثلا یکی از آتم هامون لایک میشه) باعث میشه کل کش از بین بره و عملکرد برنامه خیلی تحت تاثیر قرار میده.
لطفا من رو در این مورد راهنمایی کنید

**Comment by VahidN** [comment]
[Skip invalidating the related cache entries of a given query](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor#skip-invalidating-the-related-cache-entries-of-a-given-query)
