### ISSUE TITLE
CacheQueriesContainingTableNames - Exclusive list

### ISSUE THREAD

**Issue by paladinu** [VahidN/EFCoreSecondLevelCacheInterceptor#159]
# Summary of the issue

Need support for exclusive list of tables.  `CacheQueriesContainingTableNames` is very useful functionality but it seems to be sweeping up volatile tables into cache when they are joined/included with cachable tables.  I was imagining a CacheQueriesContaining`Only`TableNames function that would provide and exclusive list of table names so that, if a query included any table name that was not in the list, it would not be cached.  Is there a way to do this already that I am missing or not understanding?

## Environment

```
.NET (Core) SDK version: 3.1
Microsoft.EntityFrameworkCore version:  3.1.11
EFCoreSecondLevelCacheInterceptor version:  3.0.0
Database: (e.g. SQL Server, SQLite, etc.): MySQL
Cache provider: (e.g. in-memory, redis, etc.): in-memory + redis
```

## Example code/Steps to reproduce:
Expecting just the tblAppSetting data to get cached.
```
var tablesToCache = new List<string> {
                        "tblAppSetting"
                    };
                    options.CacheQueriesContainingTableNames(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(efCacheTimeoutMin), tablesToCache.ToArray());
```
But queries involving both volatile customer data and `tblAppSetting` cause the volatile data to be cached as well.

## Output:

```
Exception message: NA
Full Stack trace: NA
```

**Comment by VahidN** [comment]
If you click at the provided link you can find [this new option](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/9b29fe8a167f2188985c0426ea42ed6ecf1c5d2c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R368).

**Comment by paladinu** [comment]
Also @VahidN let me know if you prefer me to open a new issue.
