### ISSUE TITLE
Possibly change to Debug

### ISSUE THREAD

**Issue by jasenf** [VahidN/EFCoreSecondLevelCacheInterceptor#16]
There's a TON of logging that the cache code is dumping into our production logs.  Can we get this to work like the previous version?  No logging unless it's in debug mode?

This is flooding production level deployments that keep Info on.

**Comment by VahidN** [comment]
What's the minimum log level of your production system? It should be `Warning`:
```
  public enum LogLevel
  {
    Trace,
    Debug,
    Information,
    Warning,
    Error,
    Critical,
    None,
  }
```
If you are logging too much info, your minimum log level is wrong and lower than or equal to `Information`.

**Comment by jasenf** [comment]
Every production system I've ever worked with has been set to Information.  That article basically says the even .netcore default is Information.   Information level is used to log standard trace events that we may need to reference in production (typically custom inquiry, help desk support) cases. 

This is the only library, out of HUNDREDS of Nuget packages we implement, that is doing Information level logging.    I may be in the minority but I would consider Cache keys very much debug data.

Thanks for your continued work on this awesome library!

**Comment by VahidN** [comment]
Changed it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/66a08bcac0ec2ab310a9e50072464d248a3a36a7
