### ISSUE TITLE
Thread pool exhaustion using easycache with Redis

### ISSUE THREAD

**Issue by john2094** [VahidN/EFCoreSecondLevelCacheInterceptor#164]
# Summary of the issue
### This library causes thread pool exhaustion using easycache in high concurrency scenarios.

I have a netcore6 api that works fine in development environment scenarios, After a long research and tests i figured it out that this library (and other stuff in my code that is already fixed) causes a thread pool exhaustion (I use [this tutorial]( https://docs.microsoft.com/en-us/shows/on-net/diagnosing-thread-pool-exhaustion-issues-in-net-core-apps) to detect it). 

I realized that calls to easycaching provider was made with `get` and `set` methods instead of `getAsync` and `setAsync`  variations. I supose this cause that thread pool grows and eventuallly causes timeouts in service.

I cloned this repo and made these modifications (using https://github.com/kpreisser/AsyncReaderWriterLockSlim in  ReaderWriterLockProvider instead of ReaderWriterLockSlim), also I changed another process that use intense CPU like `ComputeHash` and the `GetEFCacheKey` functions turning them in asynchronous functions, but still with this changes, thread pool exhaustion persists.

 

## Environment

```
.NET (Core) SDK version: 6.0
Microsoft.EntityFrameworkCore version: tested in 6.0.3 and 6.0.6
EFCoreSecondLevelCacheInterceptor version: tested with 3.6.1 and 3.1.1
Database: SQL Server
Cache provider:  redis
```

## Example code/Steps to reproduce:
`statup.cs`
```C#
...
const string providerName1 = "Redis1";

builder.Services.AddEasyCaching(option =>
{
    option.UseRedis(config =>
    {
        config.DBConfig.AllowAdmin = true;
        config.DBConfig.Password = "password123";
        config.DBConfig.SyncTimeout = 10000;
        config.DBConfig.AsyncTimeout = 10000;
        config.DBConfig.Endpoints.Add(new EasyCaching.Core.Configurations.ServerEndPoint("SERVER", PORT));
    }, providerName1).WithMessagePack(providerName1);
});
builder.Services.AddEFSecondLevelCache(options =>
    options.UseEasyCachingCoreProvider(providerName1, isHybridCache: false).DisableLogging(true).UseCacheKeyPrefix("EF_").CacheAllQueries(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(30))
    );
    

builder.Services.AddDbContextPool<ApplicationDbContext>((serviceProvider, optionsBuilder) =>
    optionsBuilder
        .UseSqlServer(
            connectionString,
            sqlServerOptionsBuilder =>
            {
                sqlServerOptionsBuilder
                    .CommandTimeout((int) TimeSpan.FromMinutes(3).TotalSeconds)
                    .EnableRetryOnFailure()
                    ;
            })
        .AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>())
    );


...
```

### K6 script to stress service

```js
const user3 =[];//A list of random user ids
export const options = {

  thresholds: {},
  scenarios: {
    pa: {
        executor: 'ramping-vus',
        startVUs:100,
        stages: [
          { duration: '30s', target: 400 },
          { duration: '30s', target: 10 },
        
        ],
        gracefulRampDown: '70s',
        exec: 'cmhar',
      }
  },
}
export function cmhar() {
  let response

  const user = randomItem(user3);
 
 const userHeader = {}
 userHeader[filedUserHeaderName]=user;
 response=http.get(`https://localhost:7006/UserContoller?id=${user}`)
}
```
 

### Timeout on call api

![Grabación_área-de-selección_20220619202754](https://user-images.githubusercontent.com/20388897/174506770-781d3046-6ea2-4681-b7e6-c4f3293f4fe4.gif)

Thanks for your help!

**Comment by VahidN** [comment]
Yes, This library and also [other libraries use locks](https://github.com/dotnetcore/EasyCaching/search?q=lock). This is how it works and without it there be a lot of issues. We are not living in a pure world, live with it.
