### ISSUE TITLE
EasyCaching Redis Connectionexception

### ISSUE THREAD

**Issue by mischa71lab** [VahidN/EFCoreSecondLevelCacheInterceptor#166]
Hello, 

I'm using EasyCaching Redis provider and when the redis server is not available i get a n exception.
I would like the web-api to continue working even when the redis cache is offline.
Where should i handle this exception? Can i override a method somewhere?

` StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET EF_9F7E8CF1DC8DDA2E; It was not possible to connect to the redis server(s). `

**Comment by VahidN** [comment]
You should use [EasyCaching.HybridCache](https://easycaching.readthedocs.io/en/latest/Hybrid/) for your scenario.
