### ISSUE TITLE
 Unable to cast object of type 'HierarchyId'

### ISSUE THREAD

**Issue by exytab** [VahidN/EFCoreSecondLevelCacheInterceptor#170]
# Summary of the issue

I use `https://github.com/efcore/EFCore.SqlServer.HierarchyId` library that support `HierarchyId` type. 
But I cannot cast value to `HierarchyId` type when read entity. 
Can you support this library? 

## Setup

```csharp
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
 optionsBuilder.UseSqlServer(
    connectionString,
    x => x.UseHierarchyId());
}
```

## Environment

```
.NET (Core) SDK version: 6.0.7
Microsoft.EntityFrameworkCore version: 6.0.7
EFCoreSecondLevelCacheInterceptor version: 3.6.2
Database: SQL Server
Cache provider: in-memory
```

## Output:

```
Exception message:

An exception occurred while iterating over the results of a query for context type 'ApplicationDbContext'.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.
File name: 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
```

**Comment by bzbetty** [comment]
Also experiencing this.

```
System.Private.CoreLib: Exception while executing function: GraphQL. System.Private.CoreLib: Unable to cast object of type 'Microsoft.SqlServer.Types.SqlHierarchyId' to type 'Microsoft.Data.SqlClient.Server.IBinarySerialize'.
```

Is this just a matter of adding it as a binary type like https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFDataReaderLoader.cs#L269 ?

I'm assuming there's no way to currently extend EFDataReaderLoader?

**Comment by bzbetty** [comment]
* Copied Microsoft.SqlServer.Types from Issue4SpatialType project got passed the first Microsoft.SqlServer.Types error (suspect it will die later due to HierarchyId referencing a different version)

* Added the following 
```
private bool isBinary(int ordinal)
    {
        var typeName = _tableRows.GetFieldTypeName(ordinal);

        return string.Equals(typeName, "Microsoft.SqlServer.Types.SqlGeography", StringComparison.Ordinal)
               || string.Equals(typeName, "Microsoft.SqlServer.Types.SqlGeometry", StringComparison.Ordinal)
               || string.Equals(typeName, "Microsoft.SqlServer.Types.SqlHierarchyId", StringComparison.Ordinal)
              ;
    }
```

Which then leads to:

```Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'```

Which seems like much more of an underlying issue that wouldn't be easy to solve, maybe i went down the wrong path.

**Comment by bzbetty** [comment]
Is this closed as fixed? I don't see anything in the git history that suggests it was.

**Comment by VahidN** [comment]
It's the same as https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/4. It can be done.
