### ISSUE TITLE
Use with Entity Framework 6 and asp.net MVC

### ISSUE THREAD

**Issue by ShubhamSawant** [VahidN/EFCoreSecondLevelCacheInterceptor#171]
# Summary of the issue

Hi @VahidN @RyanThomas73 @dikklop 
I wanted to use the EFCoreSecondLevelCacheInterceptor library with EntityFramework 6 version so I have set it up according to docs as well but when I use Cacheable() extension method  in one of the query expressions I get the below error

**`Cacheable` method is designed only for relational EF Core queries.**

is this supported with EntityFramework version 6?

Technology:- Asp.Net MVC, Entity Framework 6, Azure SQL Server, .Net framework 4.8

**Comment by VahidN** [comment]
> is this supported with EntityFramework version 6?

No. This library is designed for EF-Core and [you can use](https://docs.microsoft.com/en-us/archive/msdn-magazine/2016/october/data-points-run-ef-core-on-both-net-framework-and-net-core) EF-Core with .NET 4.8.
