### ISSUE TITLE
Cache returns stale information.

### ISSUE THREAD

**Issue by cewee** [VahidN/EFCoreSecondLevelCacheInterceptor#177]
# Summary of the issue

Cache returns stale information.

## Environment

```
.NET (Core) SDK version:  net6.0
Microsoft.EntityFrameworkCore version:  6.0.9
EFCoreSecondLevelCacheInterceptor version: 3.6.3
Database:  SQL Server (with Microsoft.EntityFrameworkCore.SqlServer Version="6.0.9")
Cache provider: InMemory
```

## Example code/Steps to reproduce:

Setup:
```
        services.AddEFSecondLevelCache(options =>
                {
                    options.UseMemoryCacheProvider().DisableLogging(true).UseCacheKeyPrefix("EF_");
                    options.CacheAllQueries(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(60));
                }
            );

[...]

        options.AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>());
```

Application has exclusive access to database (no one else does any writes).

## Output:

One Loop constantly reads a database table to check if a new /unassigned job is present.
Somewhere else new jobs are added. 

Sometimes it happens that only one job is returned by the query (when in fact there are to in the database), as long as no other jobs are added, the query will alway return this old value. Manually invalidating the cache, solves the issue, and two jobs are again returned.

Is it possible that there is the following concurrency issue: (T1 = Thread 1, T2 = Thread 2)

T1: Insert Job 
T1: Invalidate JobTable
T2: Query Jobs
T2: Table dirty -> actual DB Query
T1: Writes new data to DB
T2: Updates Cache with result from BEFORE T1 write was finished

and then consecutive Reads will all hit the stale cache value ?

The actual read query is the following:

```
        var dbSet = _appDbContext.Set<JobTable>().TagWith("ReturnUnstartedJobs");
        return await dbSet.Where(o => o.JobAssingedToWorker== null).Select(o => o.Id).ToListAsync(cancellationToken);
```

**Comment by VahidN** [comment]
A memory-cache exists inside of an IoC container (or a .BuildServiceProvider()). If you have multiple IoC containers, they won't see each other. In this case you should use a distributed cache such as Redis.

**Comment by cewee** [comment]
Hi, thank you for quick response!
We're  using only one IoC.
Trying to trace down the issue, i arrived  at the following function [ProcessExecutedCommands](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/e99632c36cc6036384da6be2f33102a38546e38d/src/EFCoreSecondLevelCacheInterceptor/DbCommandInterceptorProcessor.cs#L53)

In our project this function may be triggered simultanously (originating from different contexts)

I could see a concurrency issue if lines 74-77 (invalidating a cache result)
are executed in parallel to any of the cases in lines  85-119 (setting a new cache value)


(Note: I saw that my original description of the concurrency issue cannot happen, as the invalidation seems to happen after the data has been written to the DB. However if might still occur if Write and Read happen at the same time).

**Comment by VahidN** [comment]
[I have some parallel tests here and it works just fine](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/EFCacheServiceProviderTests.cs#L234).
