### ISSUE TITLE
Unable to use Azure Cache for Redis

### ISSUE THREAD

**Issue by hallidev** [VahidN/EFCoreSecondLevelCacheInterceptor#18]
# Summary of the issue

I just switched from EFCoreSecondLevelCache (the old package) to this new package, and I'm unable to get Redis caching to work using Azure Cache for Redis. I have a Standard Tier Redis cache configured in Azure like so:

![image](https://user-images.githubusercontent.com/16142069/78379605-a1eb7000-75a0-11ea-9d86-beae565a9d1e.png)

The Redis cache config looks like this:

```
                cacheConfigurationBuilder
                    .WithJsonSerializer(cacheJsonSerializerSettings, cacheJsonSerializerSettings)
                    .WithRedisConfiguration(RedisCacheConfigKey, config =>
                    {
                        config.WithAllowAdmin()
                            .WithPassword(redisConfig.Password)
                            .WithDatabase(0)
                            .WithSsl(redisConfig.Endpoint)
                            .WithEndpoint(redisConfig.Endpoint, redisConfig.Port)
                        .EnableKeyspaceEvents();
                    })
                    .WithRedisCacheHandle(RedisCacheConfigKey)
                    .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10));
```

With all of the above, any query run against the DbContext throws this exception:

'ERR unknown command `CONFIG`, with args beginning with: `GET`, `notify-keyspace-events`, '

Stack Trace:

   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2231
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisServer.cs:line 585
   at StackExchange.Redis.RedisServer.ConfigGet(RedisValue pattern, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisServer.cs:line 152
   at CacheManager.Redis.RedisConnectionManager.GetConfiguration(String key)
   at CacheManager.Redis.RedisCacheHandle`1..ctor(ICacheManagerConfiguration managerConfiguration, CacheHandleConfiguration configuration, ILoggerFactory loggerFactory, ICacheSerializer serializer)

**Comment by VahidN** [comment]
This error is related to `EnableKeyspaceEvents()` setting.

> It enables keyspace notifications to react on eviction/expiration of items.
> Make sure that all servers are configured correctly and 'notify-keyspace-events' is at least set to 'Exe', otherwise CacheManager will not retrieve any events.
> See https://redis.io/topics/notifications#configuration for configuration details.
> 

If you can't set it, just remove that line.

**Comment by hallidev** [comment]
@VahidN Appreciate the quick response. Great library by the way, I've been relying on it for a while now.

When I remove ```EnableKeyspaceEvents()```, all my queries throw the following exception:

   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetInt16(Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by VahidN** [comment]
- You can try `Egx` or `eA` value for the `notify-keyspace-events` too.
- What's your settings for `GetInt16` field? What db is in use?

**Comment by hallidev** [comment]
On closer inspection, only ```.Cacheable()``` queries are throwing the ```NullReferenceException```. I've tried switching between the keyspace event types - same result.

It's not just ```GetInt16``` that's failing - it seems it fails on any ```GetXXX`` call with the ```NullReferenceException```.

What do you mean by settings for ```GetInt16``` though?

Also, I'm using an Azure SQL database.

**Comment by VahidN** [comment]
Probably you have nullable property. It's fixed via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/b172fed5d1d8e749b83cf3bcf2d354bc5292e24d

**Comment by hallidev** [comment]
Ah yes - I have many nullable properties. I'm sure that's it.

Funny enough, I installed 1.4.0 this morning and noticed you released 1.5.0 shortly afterwards. Will you be pushing another nuget package?

Again, your work on this is very much appreciated.

**Comment by hallidev** [comment]
I just took a quick at your change - would it only affect Redis caching? The in-memory caching seems to be working fine, but I'm not sure if that uses a totally different mechanism.

**Comment by VahidN** [comment]
NuGet's site waits for 5 minutes to make the uploaded package public. It's public now.

**Comment by hallidev** [comment]
Just took the package and it does get quite a bit further, but ultimately fails on objects that have a nullable DateTime:

```
System.InvalidCastException: 'Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.'

   at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__22`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleOrDefaultAsync>d__22`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

None of my values are stored as DateTimeOffset - they're all defined like this:

```
public DateTime? LastLoginUtc { get; set; }
```

**Comment by VahidN** [comment]
Try setting:
```C#
var jss = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                TypeNameHandling = TypeNameHandling.Objects, // set this if you have binary data

                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateParseHandling = DateParseHandling.DateTimeOffset,
                DateTimeZoneHandling = DateTimeZoneHandling.Utc,
            };
```

**Comment by VahidN** [comment]
This is a better solution and converts special data types correctly:
```C#
var jss = new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore,
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
    TypeNameHandling = TypeNameHandling.Objects, // set this if you have binary data
    Converters = { new SpecialTypesConverter() }
};
```
And [here is](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L21) the definition of the SpecialTypesConverter.

**Comment by hallidev** [comment]
So strange - I'm still getting the same exception. 

I should have mentioned this above, but I've been using the following JsonSerializerSettings with EFCoreSecondLevelCache for a long time:

```
            var cacheJsonSerializerSettings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Auto,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };
```

When I'm developing locally I use CacheManager's memory cache, and in other environments use Redis.

My memory cache config looks like this, and is currently working fine with the new package:

```
            cacheConfigurationBuilder
                .WithJsonSerializer(cacheJsonSerializerSettings, cacheJsonSerializerSettings)
                .WithMicrosoftMemoryCacheHandle()
                .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10));
```

I'd be surprised if this was serialization related as these serialization settings have been working so reliably for so long, but I'll admit I have no clue what the internals of your package look like.

**Comment by VahidN** [comment]
[The mentioned solution](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/18#issuecomment-608985020) has been tested with [this entity](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests.DataLayer/Entities/User.cs#L6) will all of the possible data types.

**Comment by hallidev** [comment]
Just in case this helps anyone in the future -

My issue with the DateTime conversion all boiled down to the property ```LockoutEnd``` stored on the base IdentityUser class. This property is a ```DateTimeOffset``` rather than ```DateTime```. 

The proper date type information was being lost as @VahidN points out, and his fix looks to be the correct fix. The issues I was experiencing after implementing the ```SpecialTypesConverter``` were related to other spots in code where I use the Redis cache unrelated to EFCoreSecondLevelCacheInterceptor.

My problem was here:

```TypeNameHandling = TypeNameHandling.Objects,```

My unrelated caching code started deserializing to the JObject type after introducing ```TypeNameHandling.Objects```.

Switching back to ```TypeNameHandling.Auto``` along with the use of ```SpecialTypesConverter``` fixed my issue.

My serializer settings now look like this:

```
            var cacheJsonSerializerSettings = new JsonSerializerSettings
            {
                Converters = { new StrongDateTypesConverter() }, 
                TypeNameHandling = TypeNameHandling.Auto,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };
```

I guess the takeaway is to be sure to be careful with your serializer settings.

**Comment by hallidev** [comment]
@VahidN Upon further testing with this I discovered that the serialization solution wasn't working, but due to time constraints had to move on. I've been temporarily using CacheManager.Core's memory provider to get around the issue.

I just had some time to come back to this and do some more digging, and it turns out that the ```SpecialTypesConverter``` prevents the app from crashing, but leaves all nullable types null and non-nullable types as their default value.

The following console app demonstrates this:

```
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SerializeTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var cacheJsonSerializerSettings = new JsonSerializerSettings
            {
                // Types like DateTimeOffset don't work properly with EFCoreSecondLevelCacheInterceptor without storing additional information about the date type
                Converters = { new SpecialTypesConverter() },
                TypeNameHandling = TypeNameHandling.Auto,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,

            };

            var dto = new MyDto
            {
                MyDate = DateTime.Now,
                MyNullableDate = DateTime.Now,
                MyOffset = DateTimeOffset.Now,
                MyNullableOffset = DateTimeOffset.Now
            };

            var json = JsonConvert.SerializeObject(dto, cacheJsonSerializerSettings);
            var dto2 = JsonConvert.DeserializeObject<MyDto>(json, cacheJsonSerializerSettings);
        }
    }

    class MyDto
    {
        public DateTime MyDate { get; set; }
        public DateTime? MyNullableDate { get; set; }
        public DateTimeOffset MyOffset { get; set; }
        public DateTimeOffset? MyNullableOffset { get; set; }
    }

    public class SpecialTypesConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(TimeSpan) || objectType == typeof(TimeSpan?)
                                                  || objectType == typeof(DateTime) || objectType == typeof(DateTime?)
                                                  || objectType == typeof(DateTimeOffset) || objectType == typeof(DateTimeOffset?);
        }

        public override bool CanRead => true;

        public override bool CanWrite => true;

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue,
            JsonSerializer serializer)
        {

            return reader.Value;
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("$type");
            writer.WriteValue(value.GetType().FullName);
            writer.WritePropertyName("$value");
            writer.WriteValue(value);
            writer.WriteEndObject();
        }
    }
}
```

When trying to implement ```ReadJson```, I fell down a rabbit hole of date parsing.

At the end of the day, I'm trying to determine why this is necessary though. ```JsonConvert``` handles serialization of all of these types with no issue. You can see this by taking the above code and simply commenting out the ```SpecialTypesConverter```. Everything serializes and deserializes fine.

EF Core also handles these system types seamlessly. 

Finally, the previous version of your package didn't have an issue with any of these types.

I took a look at your implementation and I believe this can be handled entirely within your library, though I'll admit I'm not sure of the best place to handle it.

Using ```DateTime``` / ```DateTimeOffset``` as an example, the crux of the issue is that after a result is pulled from the cache, despite having the actual type information in ```ColumnsInfo```, the ```object[]``` in ```TableRow.Values``` has defaulted to ```DateTime``` as opposed to the type stored in ```ColumnsInfo``` (which in this case is ```System.DateTimeOffset```).

If you disagree that the library should handle this, do you have any suggestions on how it could be implemented in the ```SpecialTypesConverter``` without essentially re-implementing Json.NET's handling of it?
