### ISSUE TITLE
EF7 - Cache does not invalidates after update / SaveChanges

### ISSUE THREAD

**Issue by alienwareone** [VahidN/EFCoreSecondLevelCacheInterceptor#181]
Entity Framework 7 will by default only creates a transaction "WhenNeeded":
https://github.com/dotnet/efcore/pull/28711/files#diff-d37efe7ab52549252e70561b732e0c984628fec2d024b8520771dd151444ed15R435

This will break the cache invalidation process:
https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/73ae65730dd149e12768f2916380a32879f4e5db/src/EFCoreSecondLevelCacheInterceptor/DbCommandInterceptorProcessor.cs#L221

Workaround:
```
    public ApplicationDbContext(DbContextOptions options) : base(options)
    {
        Database.AutoTransactionBehavior = AutoTransactionBehavior.Always;
    }
```

**Comment by VahidN** [comment]
There is no problem with .NET 6. [I have lots testes for it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests).
