### ISSUE TITLE
Different interceptors for different dbcontext

### ISSUE THREAD

**Issue by ThatDeveloper** [VahidN/EFCoreSecondLevelCacheInterceptor#182]
I have an application with multiple dbcontexts. I would like to configure 2x EFCoreSecondLevelCacheInterceptor with different options. Any advice? I think this would be great feature.

**Comment by VahidN** [comment]
This library uses [these services](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFServiceCollectionExtensions.cs#L16). You should provide them based on the current tenant, [like this](https://gunnarpeipman.com/aspnet-core-tenant-based-dependency-injection/). Also if you provide different connecting strings, they [will be used](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L82) as well.

**Comment by ThatDeveloper** [comment]
Thank you for the answer but this is not the solution sadly. I know the links you shared as I looked into this. I am using a similar approach, but my tenants are not known at runtime when Service Prodiver gets built. Therefore I can not do that. I need a solution like the o configuring to specify the cache provider key as an example.

**Comment by VahidN** [comment]
Here is an example about how to set the connection string based on a session value dynamically at run-time:
```C#
namespace TestBackend
{
  public class Startup
  {
    // ...

    public void ConfigureServices(IServiceCollection services)
    {
      // ...

      services.AddHttpContextAccessor();
      // + services.AddSession() && app.UseSession()
      services.AddDbContext<TestContext>((serviceProvider, options) =>
      {
        options.UseSqlServer(GetConnectionString(serviceProvider));
      });

      // ...
    }

     // ...

    private string GetConnectionString(IServiceProvider serviceProvider)
    {
      var connectionStringTemplate = Configuration.GetConnectionString("ConnectionTemplate");

      try
      {
         var httpContextAccessor = serviceProvider.GetRequiredService<IHttpContextAccessor>(); // This needs services.AddHttpContextAccessor();
         var dbName = httpContextAccessor.HttpContext.Session.GetString("databasename"); // This needs services.AddSession(); && app.UseSession();
         return connectionStringTemplate.Replace("{db_Name}", dbName);
      }
      catch(Exception ex)
      {
           var logger = serviceProvider.GetRequiredService<ILoggerFactory>().CreateLogger(nameof(Startup));
           logger.LogError("GetConnectionString error", ex, "Failed to get connection string.");
      }

      return connectionStringTemplate.Replace("{db_Name}", "---Default-DB-Name-Here---");
    }
  }
}
```

**Comment by ThatDeveloper** [comment]
@VahidN Thank you, but I already got that part. What is missing for me is the Cache part. E.x. the redis cache / cache key provider.
Imagine this: Your tenant has its own database because he needs data seperation as of compliance and now the cache would be shared with thousands of other tenants. I need the ability to specify which cache to use, per context configuration.

As an example, when I use `dbOptions.AddInterceptors(ServiceProvider.GetRequiredService<SecondLevelCacheInterceptor>());`, at that point I would need to say okay, use redis1xyz.

**Comment by ThatDeveloper** [comment]
@VahidN Or I could implement it myself if the IEFCacheSeerviceProvider would have a field within EFCacheKey that points to the DbContext used.

```
public void InsertValue(EFCacheKey cacheKey, EFCachedData value, EFCachePolicy cachePolicy)
{
    if (cacheKey.DbContext == typeof(CoreContext)){//use different cache}
    else if (cacheKey.DbContext == typeof(TenantApplicationContext)){//get tenant id and cache of tenant}
}
```

**Comment by ThatDeveloper** [comment]
@VahidN Created a PR https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/pull/183
Please have a look if that could be a fast solution.
