### ISSUE TITLE
Scoped?

### ISSUE THREAD

**Issue by ThatDeveloper** [VahidN/EFCoreSecondLevelCacheInterceptor#185]
Is it possible to have EFCoreSecondLevelCache being scoped? DbContexts are scoped too, that is why I am asking. I need this to add scoped data, e.x. data from httpcontext.

**Comment by VahidN** [comment]
No. Scoped data will be disappeared at the end of the scope but a cache is like a global static variable available throughout the whole app.

**Comment by ThatDeveloper** [comment]
@VahidN I know that. And I use redis cache. But I want the efcachingprovider to be scoped.
I am using a custom caching provider. `UseCustomCacheProvider<CustomServiceEFCacheServiceProvider>()` <--- want this scoped

**Comment by VahidN** [comment]
Use the `Find` the method of EF without this library. It's a `first level` cache This library is not designed for your app.
