### ISSUE TITLE
Manual Redis help

### ISSUE THREAD

**Issue by SyntaxEvg** [VahidN/EFCoreSecondLevelCacheInterceptor#189]
Hello, could you write a complete instruction on how your build(**EFCoreSecondLevelCacheInterceptor** ) 
and _Redis_ Docker work / HOW to allocate the cache more efficiently, I read it but I don’t get it(, can I ask you step by step? 
Stack .net 6

**Comment by VahidN** [comment]
https://anduin.aiursoft.cn/post/2020/5/14/ef-second-layer-cache-to-enhance-your-sql-database-performance-based-on-redis
