### ISSUE TITLE
How to use in a separate project

### ISSUE THREAD

**Issue by devalot76** [VahidN/EFCoreSecondLevelCacheInterceptor#19]
Hi,
My solution consists of two projects: one for the web stuff (ASP.NET Core MVC 3.1) and one for the data stuff (entities, DbContext, repositories etc.. using EF Core 3.1).
Now, I'd like to add your library in the data project **only**: can you please show my how to do that? 

Thank you.
Best regards.

**Comment by VahidN** [comment]
Your data project will be loaded by your web project at the end. So [register the required services as normal](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.AspNetCoreSample/Startup.cs#L24), and then use the `Cachable()` method in your data project.
