### ISSUE TITLE
Cache is not invalidated correct after updating an item

### ISSUE THREAD

**Issue by SebastianFreund** [VahidN/EFCoreSecondLevelCacheInterceptor#191]
# Summary of the issue
We use the EFCoreSecondLevelCacheInterceptor together with EasyCaching since some month an in the last time we had often the problem, that updated data are not displayed correct. The data get updated in the SQL database but the frontend shows the old data. It happens in most cases if the software runs some days and after a restart everything works correct again.

After some testing and debugging it looks like that the cache key gets not invalidated if the data are updated.
But the error was only reproducable if I reduce the SizeLimit. 
I used also your source to debug and what I found out was the following:

I started the software and clicked around in one table that every data are cached (The number of requests was about 15; Cache sizelimit was 10). Then I switched the page, loaded the data (one request) and switch back to the previous page. Then I updated something and sometimes the "ClearDependencyValues"-Method in the EFeasyCachingCoreProvider was called with all the dependencys (cached requests) for the table and they were removed --> everything works correct.

But sometimes in the "ClearDependencyValues"-Method where only two or three dependenyKeys even if I clicked on much more items before (about 15). Then the update was done but the old data where still displayed. In the Method "ProcessExecutingCommands" from DbCommandInterceptorProcessor I saw that the CacheKey for loading the data still exists with the old data (it was not deleted). If I updated again something the "ClearDependencyValues"-Method was in most cases called without any dependency for this table and the old data were loaded again because the key still exists in the cache.
Sometimes it helps to click around in the application (I think because then the old cacheKeys were deleted regarding the sizelimit) but otherwise the data were not displayed correct (still the old ones).

So my assumption is that cacheKey for the table with all dependenies was deleted from cache because of sizeLimit but the cacheKey with the data was not deleted. Than if the data are updated the cacheKey with the old data can not be deleted because the mapping to the table was deleted through the deletion of the table-cachekey. This is why it loads the old data until also the "old" cachekey for the data was deleted from the cache.
But that's only a guess from myside. For sure it can be something else...
It would be nice if you can check it.

## Environment

```
.NET (Core) SDK version: .NET Core 3.1
Microsoft.EntityFrameworkCore version:  5.0.8
EFCoreSecondLevelCacheInterceptor version: 3.8.1
Database: (e.g. SQL Server, SQLite, etc.) SQL Server 2017
Cache provider: (e.g. in-memory, redis, etc.) EasyCaching.InMemory 1.7.0
```

## Example code/Steps to reproduce:

That was my configuration for testing.
For production we use the default values of InMemoryCachingOptions.

```
            const string CachingProvider = "InMemoryCachingProvider";
            services.AddEFSecondLevelCache(options =>
                options.UseEasyCachingCoreProvider(CachingProvider)
                .DisableLogging(true)
                .UseCacheKeyPrefix("EF_")
                .CacheAllQueries(CacheExpirationMode.Sliding, TimeSpan.FromDays(3))
            );

            services.AddEasyCaching(options =>
            {
                // use memory cache with your own configuration
                options.UseInMemory(config =>
                {
                    config.DBConfig = new InMemoryCachingOptions
                    {
                        // scan time, default value is 60s
                        ExpirationScanFrequency = 10,
                        // total count of cache items, default value is 10000
                        SizeLimit = 10,
                        // enable deep clone when reading object from cache or not, default value is true.
                        EnableReadDeepClone = true,
                        // enable deep clone when writing object to cache or not, default value is false.
                        EnableWriteDeepClone = false,
                    };
                    // the max random second will be added to cache's expiration, default value is 120
                    config.MaxRdSecond = 120;
                    // whether enable logging, default is false
                    config.EnableLogging = true;
                    // mutex key's alive time(ms), default is 5000
                    config.LockMs = 5000;
                    // when mutex key alive, it will sleep some time, default is 300
                    config.SleepMs = 300;
                }, CachingProvider);
            });
```

**Comment by VahidN** [comment]
- I should be able to reproduce a problem. I can't turn your story to a test.
- `SizeLimit = 10` and `ClearDependencyValues` didn't work. Yes, it won't work. It needs more space.
- Don't use easy-caching if you are going to use a memory cache. It was added to support Redis and nothing else. Use the built-in one for memory caching.

**Comment by SebastianFreund** [comment]
Thanks a lot for your fast response!

Then we will switch to the build-in memory caching and hope the errors will not occure any more.

And if it is not recommended to use the inmemory cache from easy-caching I would remove this from your description
_Here you can use the [EasyCaching.Core](https://github.com/dotnetcore/EasyCaching), as a highly configurable cache manager too. To use its in-memory caching mechanism, add this entry to the .csproj file:_
Or add a hint that the SizeLimit has to be greater then the expected CacheKey count.
