### ISSUE TITLE
MERGE statements aren't detected by IsCrudCommand

### ISSUE THREAD

**Issue by bzbetty** [VahidN/EFCoreSecondLevelCacheInterceptor#192]
# Summary of the issue
MERGE statements currently rely on the INSERT/UPDATE being on a newline which isn't always the case

https://github.com/borisdj/EFCore.BulkExtensions doesn't add newlines before it's INSERT/UPDATE statements in bulk actions meaning the two libraries don't play nicely.  Currently manually clearing the cache when we use one of these commands.

**Comment by VahidN** [comment]
[EF 7x supports bulk operations](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#executeupdate-and-executedelete-bulk-updates). Have you tried it?

**Comment by bzbetty** [comment]
Thanks!
