### ISSUE TITLE
OpenTelemetry: Spans aren't created 

### ISSUE THREAD

**Issue by nkz-soft** [VahidN/EFCoreSecondLevelCacheInterceptor#194]
Spans are not created when I use EFCoreSecondLevelCacheInterceptor with OpenTelemetry for SELECT statements, but everything works fine for INSERT statements.

## Environment

```
.NET (Core) SDK version:  .NET Core 7.0, OpenTelemetry 1.4.0-rc.3
Microsoft.EntityFrameworkCore version: 7.0.2
EFCoreSecondLevelCacheInterceptor version:  3.8.2
Database: (e.g. SQL Server, SQLite, etc.) PostgreSQL (Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1)
Cache provider: (e.g. in-memory, redis, etc.) EasyCaching.CSRedis 1.8.0

```

## Example code/Steps to reproduce:

```csharp
builder.Services
    .AddNgpSqlPersistence(configuration, (provider, optionsBuilder)
        => optionsBuilder.AddInterceptors(provider.GetRequiredService<SecondLevelCacheInterceptor>()))
...        
        
builder.Services.AddOpenTelemetry()
    .ConfigureResource(builder => builder
        .AddService(
            serviceName: Assembly.GetExecutingAssembly().GetName().Name,
            serviceVersion: Assembly.GetExecutingAssembly().GetName().Version?.ToString(),
            serviceInstanceId: Environment.MachineName))
    .WithTracing(builder => builder
        .AddAspNetCoreInstrumentation(options =>
        {
            options.EnableGrpcAspNetCoreSupport = true;
            options.RecordException = true;
        })
        .AddEntityFrameworkCoreInstrumentation(o => o.SetDbStatementForText = true)
        .AddConsoleExporter()
    )
    .StartWithHost();

**Comment by VahidN** [comment]
Yes. This how caching works. It will suppress the execution of the normal EF pipeline and replaces it with a cached instance. Thus you won't see [EntityFrameworkCoreCommandExecuting](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs#L136).

**Comment by nkz-soft** [comment]
> Yes. This how caching works. It will suppress the execution of the normal EF pipeline and replaces it with a cached instance. Thus you won't see [EntityFrameworkCoreCommandExecuting](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs#L136).

I think, this is pretty important information to have. Is there workaround for this?

**Comment by Sibusten** [comment]
I am also seeing this issue. Traces are not being generated for queries, even when the database is being accessed.

It makes sense that spans would not be created when the cache is used. However, spans *should* be generated on cache misses, when the database is accessed.
