### ISSUE TITLE
Update cache

### ISSUE THREAD

**Issue by xAdamQ** [VahidN/EFCoreSecondLevelCacheInterceptor#195]
When we use `context.SaveChanges()` and update the tracked entities, if any of these entities is cached, the cache for them will be invalidated. Now since we can intercept these write operations, why don't/can't we update the cache instead of invalidating it and re-fetching it again? Is the reason that in a concurrent scenario that we might have conflicts? Sorry for the newbie question.

## Environment

```
.NET (Core) SDK version: 7.0.102
Microsoft.EntityFrameworkCore version: 7.0.2
EFCoreSecondLevelCacheInterceptor version: 3.8.3
Database: SQL Server
Cache provider: in-memory
```

**Comment by VahidN** [comment]
> why don't/can't we update the cache instead of invalidating it

Suppose you have a list of 10,000 items. Invalidating/deleting them is much faster than finding how many of these items have been changed and then updating them one by one.

**Comment by xAdamQ** [comment]
> > why don't/can't we update the cache instead of invalidating it
> 
> Suppose you have a list of 10,000 items. Invalidating/deleting them is much faster than finding how many of these items have been changed and then updating them one by one.

It's super efficient to find an item in memory(hashing, etc..), and we have to find items anyway when we query for an item and check if it is already cached.

**Comment by VahidN** [comment]
- This library doesn't work with entities and tracking system, etc. It just watches the issued quires and their results and parameters.
- Only hash of a query (and some related data, such as its parameter values) will be cached as a key. Later this key will be queried, not the whole list of its items.

**Comment by xAdamQ** [comment]
Theoretically speaking, if we somehow found a way to update the cached entities using the issued queries, will that be enough, or could we have another issue regarding cache consistency(in the case of a simple in memory cache, not distributed).
If that is possible, I will do some research and try to integrate that here.
