### ISSUE TITLE
Unable to cast object of type 'System.UInt64' to type 'System.TimeSpan'

### ISSUE THREAD

**Issue by KryptoBeard** [VahidN/EFCoreSecondLevelCacheInterceptor#196]
# Summary of the issue

Caching a EF core object that has TimeSpan? properties. On retrieving the object from cache it throws this error trying to repopulate the object.

## Environment
```
.NET (Core) SDK version:  7
Microsoft.EntityFrameworkCore version: 7
EFCoreSecondLevelCacheInterceptor version: 3.8.3
Database: (e.g. SQL Server, SQLite, etc.) Sql Server
Cache provider: (e.g. in-memory, redis, etc.) Redis
```

## Example code/Steps to reproduce:

```
Formatters
`
                .WithMessagePack(so =>
                {
                    so.EnableCustomResolver = true;
                    so.CustomResolvers = CompositeResolver.Create(
                    new IMessagePackFormatter[]
                    {
                      DbNullFormatter.Instance, // This is necessary for the null values
                    },
                    new IFormatterResolver[]
                    {
                      NativeDateTimeResolver.Instance,
                      ContractlessStandardResolver.Instance,
                      StandardResolverAllowPrivate.Instance,
                    });
                },
                  "Pack");
`
```

## Output:
`
Unable to cast object of type 'System.UInt64' to type 'System.TimeSpan'
`
```
Exception message:  Unable to cast object of type 'System.UInt64' to type 'System.TimeSpan'
Full Stack trace:
`
InvalidCastException: Unable to cast object of type 'System.UInt64' to type 'System.TimeSpan'.
EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetFieldValue<T>(int ordinal) in EFTableRowsDataReader.cs
lambda_method28(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+AsyncEnumerator.MoveNextAsync()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
`
```

**Comment by VahidN** [comment]
What's your serializer? [Try using the MessagePack](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/Settings/EFServiceProvider.cs#L188).

**Comment by KryptoBeard** [comment]
Sorry, just put that in the original post. I'm currently using MessagePack.

**Comment by VahidN** [comment]
- I can't reproduce it. [I have a test for it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests.DataLayer/Entities/User.cs#L42) and it works with SQL Server and MessagePack.
- Plus how do you want to convert a number to TimeSpan? Using TimeSpan.FromDays, FromHours, FromMilliseconds,  FromMinutes, FromSeconds, FromTicks ?

**Comment by KryptoBeard** [comment]
No idea. The Entity that is being cached has a property of  TimeSpan? StartTime. Not sure where it is erroring out in the process, Or what it's trying to convert from a number to TimeSpan, unless that is how it is stored in cache. I

**Comment by KryptoBeard** [comment]
I think this can be closed. I just realized it's trying to convert between 2 properties of different types.  I had it set someplace as TimeSpan? and other places as TimeOnly?. Works fine with I changed it back to TimeSpan. Sorry!

**Comment by KryptoBeard** [comment]
@VahidN  Do you have a test currently with TimeOnly? It looks like that is where I'm getting an error, rather than TimeSpan, even though it's saying 'TimeSpan'. My properties it's erroring on are TimeOnly? .

**Comment by VahidN** [comment]
`TimeOnly` and `DateOnly` are not supported in EF 7x. [Wait for the EF 8x](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-1/#dateonly-timeonly-supported-on-sql-server).

**Comment by KryptoBeard** [comment]
After stepping through EFTableRowsDataReader.cs , It is determining the TimeOnly value stored as a Uint64, rather than a TimeOnly.

**Comment by VahidN** [comment]
EF 7x is not able to produce migration files for `TimeOnly` and `DateOnly` data types for SQL Server. It will throw an exception. Also its behind the scene `SqlClient` doesn't support it at all. So I can't test it properly now. I will wait for its proper support in EF 8x final.
