### ISSUE TITLE
ExpirationMode, Timeout priority when using  CacheManager.Core

### ISSUE THREAD

**Issue by ping** [VahidN/EFCoreSecondLevelCacheInterceptor#20]
# Summary of the issue

I have a question regarding the newly implemented support for CacheManager.Core.
Which ExpirationMode + Timeout is in effect when defined with  both `ConfigurationBuilder..WithExpiration()` and `Cacheable()`?

In the example code below, which cache expiration is in effect for Customers?
Is it (1) Absolute for 10 Minutes or (2) Sliding for 5 Minutes?

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version:  3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.5.1
```

## Example code/Steps to reproduce:

```csharp
// Startup.cs
services.AddEFSecondLevelCache(options =>
    options.UseCacheManagerCoreProvider().DisableLogging(true)
);

// Add an in-memory cache service provider
services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
services.AddSingleton(typeof(ICacheManagerConfiguration),
    new CacheManager.Core.ConfigurationBuilder()
        .WithJsonSerializer()
        .WithMicrosoftMemoryCacheHandle(instanceName: "MyApplicationMemoryCache")
        .WithExpiration(ExpirationMode.Absolute, TimeSpan.FromMinutes(10))
        .Build());
```

```csharp
var customers = await ApplicationDbContext.Customer
    .AsNoTracking()
    .Cacheable(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(5))
    .ToListAsync();
```
## Output:

NA

**Comment by VahidN** [comment]
Settings of the `Cacheable(...)` method will override the global settings.

**Comment by ping** [comment]
@VahidN 
How do I let `Cacheable(..)` take the default settings defined in `WithExpiration(...)`?

Calling `Cacheable()` without any argument defaults to Absolute for 30 mins.

At the moment to ensure both settings are in sync, I have to specify args explicitly.

**Comment by VahidN** [comment]
Use [this method](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFServiceCollectionExtensions.cs#L151) to specify the global settings:
```C#
options.UseCacheManagerCoreProvider(CacheExpirationMode expirationMode, TimeSpan timeout);
```

**Comment by ping** [comment]
@VahidN 

```csharp
services.AddEFSecondLevelCache(options =>
    options.UseCacheManagerCoreProvider(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(5))
        .DisableLogging(true)
);
// Add an in-memory cache service provider
services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
services.AddSingleton(typeof(ICacheManagerConfiguration),
    new CacheManager.Core.ConfigurationBuilder()
        .WithJsonSerializer()
        .WithMicrosoftMemoryCacheHandle(instanceName: "ApplicationMemoryCache")
        .WithExpiration(ExpirationMode.Sliding, TimeSpan.FromMinutes(10))
        .Build());
```

```csharp
var customers = await ApplicationDbContext.Customer
    .AsNoTracking()
    .Cacheable()
    .ToListAsync();
```

The cache settings applied is still seems to be Absolute 30 mins, when I check using MiniProfiler. 

```
-- EFCachePolicy[OnGetAsync(line 161)] --> Absolute|00:30:00|||True

SELECT c."Id", c."Name"
FROM "Customer" AS c
```

If I explicitly specify the arguments to `Cacheable(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(5))`
```
-- EFCachePolicy[OnGetAsync(line 161)] --> Sliding|00:05:00|||False

SELECT c."Id", c."Name"
FROM "Customer" AS c
```

**Comment by VahidN** [comment]
> seems to be
[It's not.](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCachePolicyParser.cs#L82)

**Comment by ping** [comment]
@VahidN 
Can you perhaps explain or look in to why the query commandText is tagged with the wrong EFCachePolicy?

**Comment by VahidN** [comment]
It's skipped to be marked again due to global settings, not wrong.
