### ISSUE TITLE
I can't use EFSecondLevelCacheInterceptor with ABP

### ISSUE THREAD

**Issue by mardemza** [VahidN/EFCoreSecondLevelCacheInterceptor#202]
# Summary of the issue
I can't use Second Level Cache interceptor with project ABP ([aspnetboilerplate](https://aspnetboilerplate.com/))

## Environment

```
.NET (Core) SDK version:  **NET 6**
Microsoft.EntityFrameworkCore version: **6.0.6**
EFCoreSecondLevelCacheInterceptor version: **3.9.2**
Database: (e.g. SQL Server, SQLite, etc.): **SQL Server** 
Cache provider: (e.g. in-memory, redis, etc.): **In-memory**
```

## Example code/Steps to reproduce:
My code
![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/63375140/849af9a1-2c83-4f9d-98f0-a217e5804ccd)

The service provider is needed here
![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/63375140/bcb4b267-da74-4d1d-8f8e-47342e2615b2)

## Output:
There is no output error, only that queries keep coming to the database

Please can you help me

**Comment by mardemza** [comment]
This is the URL https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6672  of the issue created in the ABP project repository

**Comment by VahidN** [comment]
If you have added the required services before (services.AddEFSecondLevelCache ...), just try using `IocManager.IocContainer.Resolve<SecondLevelCacheInterceptor>()` to introduce this interceptor?

**Comment by mardemza** [comment]
IocManager.IocContainer.Resolve() Does not exist but <SecondLevelCacheInterceptor>if IocManager.Instance.IocContainer.Resolve<SecondLevelCacheInterceptor>() exists but did not work
