### ISSUE TITLE
ConnectionPool Exchaustion since 3.7.0 Update

### ISSUE THREAD

**Issue by thomasstockermc** [VahidN/EFCoreSecondLevelCacheInterceptor#203]
# Summary of the issue

When a lot of parallel requests occour a ConnectionPool Exhaustion occours.

## Environment

.NET (Core) SDK version: 6.0.410
Microsoft.EntityFrameworkCore version:  7.0.5
EFCoreSecondLevelCacheInterceptor version: 3.8.8
Database: (e.g. SQL Server, SQLite, etc.): Sql Server
Cache provider: (e.g. in-memory, redis, etc.) InMemory

## Example code/Steps to reproduce:

A lot of reading Threads.

## Output:

A Memory Dump shows following Locking issue.

dozens of callstacks with this call stack parts.

```
[Waiting on Async Operation, double-click or press enter to view Async Call Stacks]	
System.Private.CoreLib.dll!System.Threading.SemaphoreSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
AsyncLock.dll!NeoSmart.AsyncLock.AsyncLock.Lock(System.Threading.CancellationToken cancellationToken)	Unknown
EFCoreSecondLevelCacheInterceptor.dll!EFCoreSecondLevelCacheInterceptor.LockProvider.Lock(System.Threading.CancellationToken cancellationToken)
EFCoreSecondLevelCacheInterceptor.dll!EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ReaderExecuting(System.Data.Common.DbCommand command, Microsoft.EntityFrameworkCore.Diagnostics.CommandEventData eventData, Microsoft.EntityFrameworkCore.Diagnostics.InterceptionResult<System.Data.Common.DbDataReader> result)
```

One call stack with this stack parts. (So meaning only one Thread is reading).

```
EFCoreSecondLevelCacheInterceptor.dll!EFCoreSecondLevelCacheInterceptor.EFDataReaderLoader.Read()
EFCoreSecondLevelCacheInterceptor.dll!EFCoreSecondLevelCacheInterceptor.EFDataReaderLoader.LoadAndClose()
EFCoreSecondLevelCacheInterceptor.dll!EFCoreSecondLevelCacheInterceptor.DbCommandInterceptorProcessor.ProcessExecutedCommands<System.Data.Common.DbDataReader>(System.Data.Common.DbCommand command, Microsoft.EntityFrameworkCore.DbContext context, System.Data.Common.DbDataReader result, EFCoreSecondLevelCacheInterceptor.EFCachePolicy cachePolicy)
EFCoreSecondLevelCacheInterceptor.dll!EFCoreSecondLevelCacheInterceptor.SecondLevelCacheInterceptor.ReaderExecuted(System.Data.Common.DbCommand command, Microsoft.EntityFrameworkCore.Diagnostics.CommandExecutedEventData eventData, System.Data.Common.DbDataReader result)
```

## Reason:

Here the IReaderWriterLock was changed to a ILockprovider not differntiating between read and write.
https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/841af803379d4a6eb0505e22e6b03c42c64eec9f

This means only one operation can be active at a time a read or a write. Before, several readers or one write could be active.

**Comment by VahidN** [comment]
You are saying you have created lots of threads and you are seeing lots of locks. Yes, that's true. This is how locking works.
