### ISSUE TITLE
Breaking change from version 3.6.* to 3.9.*

### ISSUE THREAD

**Issue by NinjaCross** [VahidN/EFCoreSecondLevelCacheInterceptor#204]
I'm using version 3.6.3, and I implemented my own inheritor of `IEntityFrameworkSecondLevelCacheProvider`
Inside that implementation, I'm using `IReaderWriterLockProvider`.
I've tried to upgrade to 3.9.*, but the code doesn't compile anymore, because `IReaderWriterLockProvider` has been removed.

Breaking changes are normal/expected for **major** version bumps, but are very unusual for **minor** versions bumps.

My suggestion is to comply with [Semantic Versioning 2.0.0](https://semver.org/) and:
1. Reintroduce `IReaderWriterLockProvider` interface and it's implementor in 3.* versions, in order to keep uniform compatibility 
2. Bump up the current release to major version to 4.*, so that user knows that there are breaking changes

**Comment by VahidN** [comment]
I don't want to do that, and you have no right to tell me what to do.
