### ISSUE TITLE
Q: Any reason not to remove all comments from sql before caculating cache key?

### ISSUE THREAD

**Issue by bzbetty** [VahidN/EFCoreSecondLevelCacheInterceptor#205]
I use .TagWith quite a bit, but I believe that means it won't share cache with other similar queries as the query is technically different.

It looks like you modify the query currently to EFCachePolicyParser.RemoveEFCachePolicyTag, wondering if it makes sense to extend this to remove all comments?

**Comment by VahidN** [comment]
If you are allergic to my decisions, don't use it.
