### ISSUE TITLE
Specifying cacheDependencies in call to Cacheable(...) does not cause invalidation

### ISSUE THREAD

**Issue by DJdaSilva** [VahidN/EFCoreSecondLevelCacheInterceptor#208]
Hi there! Thanks for this repo - very elegant solution!!

# Summary of the issue
Specifying cacheDependencies in call to Cacheable(...) does not cause invalidation when inserting to the table that was specified in the argument.

## Environment

```
.NET (Core) SDK version: 6
Microsoft.EntityFrameworkCore version: 6.0.8
EFCoreSecondLevelCacheInterceptor version: 3.9.2
Database: Sql Server
Cache provider: Redis
```

## Example code/Steps to reproduce:
```
            services.AddEFSecondLevelCache(
                options =>
                    options.UseEasyCachingCoreProvider(providerName1, isHybridCache: false)
                        .DisableLogging(false)
                        .UseCacheKeyPrefix(sp => "EF-" + sp.GetRequiredService<IContextAccessorAdapter>()
                         .GetServiceProvider()
                         .GetRequiredService<IIdentityAccessor>().UserIdentity.ClientId + "-"));
```

We have a view - energy.EnergyEmissions that loads data from the energy.Energy table. My expectation is that this query:
```
            var query = this.dbContext.EnergyEmissions
                .Where(ee => reportingPeriodIds.Contains(ee.ReportingPeriodId))
                .AsQueryable();

            if (scope != null)
            {
                query = query.Where(e => e.ConfiguredEmissionSource.Scope == scope);
            }

            if (businessUnitIds.AnySafe())
                query = query.Where(em => businessUnitIds.Contains(em.Location.BusinessUnitId));

            var results = await query.OrderBy(ee => ee.ReportingPeriod.EndDate)
                .Cacheable(CacheExpirationMode.Sliding, TimeSpan.FromHours(1), new[] { "Energy" })
                .ToArrayAsync();
```
Should result in the cache being invalidated when I insert into/delete from the energy.Energy table. However, the query doesn't get invalidated. The only thing not reflected above is that there are global query filters on the database - not sure if relevant?

Sorry if I am missing something - I did get it working using manual cache invalidation covered on the wiki so can use that if need be - but hoping to use this as it would be a lot more elegant and sure to cover all cases if my understanding of it is correct!

Thanks!

**Comment by VahidN** [comment]
You shouldn't specify that parameter. [It will tell you](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheDependenciesProcessor.cs#L92), if it's necessary. Turn on the logging to see more details.
