### ISSUE TITLE
Question - EFCachePolicy

### ISSUE THREAD

**Issue by dawson1990** [VahidN/EFCoreSecondLevelCacheInterceptor#21]
Hello,

I am trying to update the _EFCachePolicy_ in particular the _CacheDependencies_ as my table names are all appended with 
`dbo.`
command text:

`
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[ObjectRowState], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [dbo].[Users] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0

`

Within the _EFCacheDependenciesProcessor_ class and the method _GetCacheDependencies_, the argument EFCachePolicy does not match the policy  I configure within the Startup 

`
EFCachePolicy.Configure(options =>
                {
                    options.CacheDependencies("dbo.Users", "dbo.Table2");
                });
`

When debugging the Table Names inferred from the above command text results in "dbo" and  this results in the _EFUnknownsCacheDependency_ within the cache due to fact that it finds tables with 'dbo' instead of the full table name.

How do I properly configure this? 

Thanks.

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/ec12b9085d79fd4beedca2340e9d1754d56296d1
