### ISSUE TITLE
Q: Always keep values in cache when using redis persistence or faster logs?

### ISSUE THREAD

**Issue by aloksharma1** [VahidN/EFCoreSecondLevelCacheInterceptor#212]
Hello,

i am using faster & redis persistence cache techniques with my distributed project, and for most performant data availability i want to invalidate caches only when something changes in database side (any CRUD). Is this supported? if so what settings i need to do in for faster, i can see the example of redis but nothing on faster.

thanks

**Comment by VahidN** [comment]
I don't know. I'm not interested in this topic. Use something else which works for you.
