### ISSUE TITLE
Fallback on sql server database not working.

### ISSUE THREAD

**Issue by sambar-delen** [VahidN/EFCoreSecondLevelCacheInterceptor#215]
This is a follow up of a previous issue. Thanks for responding so timely. 
previous issue: https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/214

# Summary of the issue
I have added the `UseDbCallsIfCachingProviderIsDown(true)` option to the second level caching settings. However, Once I turn off the running redis server, I still get an error during the following request.  

## Environment

```
Environment is the same as the referenced issue.
.NET (Core) SDK version: 
Microsoft.EntityFrameworkCore version: 
EFCoreSecondLevelCacheInterceptor version: 
Database: (e.g. SQL Server, SQLite, etc.)
Cache provider: (e.g. in-memory, redis, etc.)
```

## Example code/Steps to reproduce:
Setup second level caching, startup with redis enabled -> shut it down -> run a request.

paste your core code

![SetupCode](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/eef267fd-265a-4f33-9388-b022b18fbdd6)
![CachingSetup](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/3a7ba77d-8e92-4189-9987-0927e1fe7014)

## Output:
![IssueScreenshot](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/ea6626d9-deab-4b58-b562-440620898f41)

Exception message:

Full Stack trace:
![Stacktrace](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/d29f8c29-9501-4f1e-b1e3-60bbb8d00438)
![Stacktrace_2](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/7cadd160-1cca-45bd-a044-e69b666bfdea)
![Stacktrace_3](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/334fa005-05af-4796-9f2b-0490ea01b0af)
![StackTrace_4](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/b71aaf3b-324f-4449-b5d7-538322634e16)

**Comment by VahidN** [comment]
Those red `ERR`'s are just [the output of](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/SecondLevelCacheInterceptor.cs#L76) `LogCritical` method calls.

**Comment by sambar-delen** [comment]
I pulled the source code locally and directly referenced it. I noticed that once the redis is down, then I do a request, the code still reaches the "_cacheService.InsertValue(...)" line. 
![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/f3a0b78e-fd99-4c7e-8e9d-7e232e1ebb0b)
This causes an error, as the redis is down obviously.

**Comment by sambar-delen** [comment]
Nevermind, I found that the Redis exception does indeed get catched. The remaining problem is that after the interception, the dbContext seems to be closed. This might be on my end. Investigating further.
<img width="508" alt="Thingies" src="https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/100549cb-88cf-4b53-afb7-61831bfa64d5">

**Comment by sambar-delen** [comment]
I have now found out that the context is not the issue, despite the error message. The problem does indeed seem to be that the insertData still happens, even though there is no connection to the reddis.

**Comment by sambar-delen** [comment]
I think I might have found the problem. The even though the result gets returned in the catch clause, the result has already been closed in the try section. 

<img width="770" alt="image" src="https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/9324c565-45fb-4303-b94f-e79026803bb7">

<img width="817" alt="image" src="https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/80c1d021-08a9-4cb8-a5c1-6ee3c06452b0">

I'm having a look for a soltion. 

For now, what do you think? @VahidN

**Comment by amir734jj** [comment]
I am having exactly the same problem.

**Comment by VahidN** [comment]
Try V 4.8.5. It will not close the active reader.

**Comment by doanhieu9797** [comment]
I am using Oracle DB and Redis cache with UseStackExchangeRedisCacheProvider version 5.1.1, but I'm still experiencing an error when Redis is down. Please help me check this.

**Comment by VahidN** [comment]
Try V 5.2.1
