### ISSUE TITLE
Make select methods virtual to ease extension of these

### ISSUE THREAD

**Issue by ErikBIMobject** [VahidN/EFCoreSecondLevelCacheInterceptor#218]
# Summary of the issue
Im trying to make this package work in a scaled out scenario while using a memorycache provider. From what I've seen this is not currently supported. 
It would make my life a lot easier if you could make InvalidateCacheDependencies and ClearAllCachedEntries of the EFCacheManagerCoreProvider virtual. Then I could override them and ensure that the memory caches are wiped on all the instances. 
If you want to make more (or all) virtual that would be nice as well =) 

Thank you!

**Comment by VahidN** [comment]
You can implement your own `IEFCacheServiceProvider` and then introduce it using the `UseCustomCacheProvider<MyProvider>()` method. If you need anything from the default implantation, just inject it into the constructor of your custom provider.
