### ISSUE TITLE
Prefix not applied to all generated keys.

### ISSUE THREAD

**Issue by sambar-delen** [VahidN/EFCoreSecondLevelCacheInterceptor#219]
# Summary of the issue
All the calls to the database are being cached correctly with the given prefixes correctly applied. However, there seem to be some extra entries in the redis database that do not follow to the prefix rules. Would this be a problem with easycaching? Or is the prefix being ignored in this package? 

## Environment

```
.NET (Core) SDK version: 6.0.416
Microsoft.EntityFrameworkCore version: 6.0.24
EFCoreSecondLevelCacheInterceptor version: 4.0.0
Database: (e.g. SQL Server, SQLite, etc.): SQL Server
Cache provider: (e.g. in-memory, redis, etc.): redis
```

## Example code/Steps to reproduce:

paste your core code
prefixes: 
![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/da3798bb-381a-4f54-9a2c-be6ab68033dd)
result: 
![RedisInsightLackingPrefix](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/129937214/db8089a2-d2aa-46cb-94d7-d99fef6e7450)

**Comment by VahidN** [comment]
Don't use the redis directly and then post these kinds of issues here.
