### ISSUE TITLE
Code releases are not tagged

### ISSUE THREAD

**Issue by pragone** [VahidN/EFCoreSecondLevelCacheInterceptor#221]
# Summary of the issue

In Nuget, there are a bunch of versions that are not reflected as tags in the Github repo (as of now: 4.0.0, 3.9.5, 3.9.4, 3.9.3, 3.9.2, 3.9.1, 3.9.0, 3.8.8, 3.8.7, 3.8.6, 3.8.5, 3.8.3, 3.8.2).

Using the Nuget package explorer I was able to find the commit hash of the version I was interested in (e.g. https://nuget.info/packages/EFCoreSecondLevelCacheInterceptor/4.0.0)
<img width="584" alt="image" src="https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/178862/1750ceb7-089b-4908-b56b-53289bdbe941">

I'm really thankful for the effort you've put into this library :) so I thought I would help. These are the hashes of each of the missing tags:
| Version | Hash |
|--------|--------|
| 4.0.0   | 429edc7ed5f2486aaa0dc58f440f3c964c5dc0ba |
| 3.9.5   | 221b463b183e83cd5c4682b6e67c6bfd85ea7a93 |
| 3.9.4   | 3ef0f1a9668185f5acd9b3f17aaf33f197665d74 |
| 3.9.3   | fef5c28be6fa4c61ef4a30be4fcceb18cb6c9daa |
| 3.9.2   | c2f45c3a6ed0717d4469b3684e02652f4b65c0e5 |
| 3.9.1   | 1ef2ee9afa8461e0e197869e6ea0947fbffd02fc |
| 3.9.0   | a5bf3e46b3e62cee8bc5dfb9fff808105dedeb8f |
| 3.8.8   | e653eba005e094a1ed366968136d9b789fc9a429 |
| 3.8.7   | f0e68e1f195eaa17b1a20aa443d968f36047d876 |
| 3.8.6   | 1b86717b1aa6fcce3e70c97db2f149943b71c7f4 |
| 3.8.5   | ba4f9b75be59b6a0f47986a15d7ee008cd60c9ec |
| 3.8.3   | 2fe0498cd923f09aa9f1ac2110cf0f74156cb3a3 |
| 3.8.2   | 4df9f38b35c2e2b7f3301524a3a94f7e6aa90d70 |

And you should be able to quickly publish this tags by doing 

```
git tag 4.0.0 429edc7ed5f2486aaa0dc58f440f3c964c5dc0ba
git tag 3.9.5 221b463b183e83cd5c4682b6e67c6bfd85ea7a93
git tag 3.9.4 3ef0f1a9668185f5acd9b3f17aaf33f197665d74
git tag 3.9.3 fef5c28be6fa4c61ef4a30be4fcceb18cb6c9daa
git tag 3.9.2 c2f45c3a6ed0717d4469b3684e02652f4b65c0e5
git tag 3.9.1 1ef2ee9afa8461e0e197869e6ea0947fbffd02fc
git tag 3.9.0 a5bf3e46b3e62cee8bc5dfb9fff808105dedeb8f
git tag 3.8.8 e653eba005e094a1ed366968136d9b789fc9a429
git tag 3.8.7 f0e68e1f195eaa17b1a20aa443d968f36047d876
git tag 3.8.6 1b86717b1aa6fcce3e70c97db2f149943b71c7f4
git tag 3.8.5 ba4f9b75be59b6a0f47986a15d7ee008cd60c9ec
git tag 3.8.3 2fe0498cd923f09aa9f1ac2110cf0f74156cb3a3
git tag 3.8.2 4df9f38b35c2e2b7f3301524a3a94f7e6aa90d70
git push --tags
```

Thanks again for the great work 👍 

## Environment

N/A

## Example code/Steps to reproduce:

N/A

## Output:

N/A

**Comment by VahidN** [comment]
Thank you. Applied.
