### ISSUE TITLE
There my be a bug?

### ISSUE THREAD

**Issue by jrlygdsj** [VahidN/EFCoreSecondLevelCacheInterceptor#223]
Hi：
when i debug to the class DbCommandInterceptorProcessor，the method ShouldSkipProcessing( ) always return true，
is there a bug?

![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/38058018/4d86e514-dfce-45de-a732-dc7571a006be)

**Comment by VahidN** [comment]
If you can debug it, step through it to see what's going on.

**Comment by jrlygdsj** [comment]
tks，i know，i should set  AllowCachingWithExplicitTransactions=true

![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/38058018/f3a1a02d-6877-420f-81f7-eda59e2100f7)
