### ISSUE TITLE
عدم نمایش کوئری کش شده در redis desktop

### ISSUE THREAD

**Issue by mbehtar** [VahidN/EFCoreSecondLevelCacheInterceptor#23]
<div dir="rtl">

سلام
کش کوئری دیتا به روشی که گفتین انجام دادم ولی اطلاعات کش شده رو نمیتونم تو ردیس دسکتاپ ببینم

**Comment by VahidN** [comment]
It's working here

![redis](https://user-images.githubusercontent.com/766010/79683276-3b23b300-823e-11ea-9819-9b5c43ef6296.png)
