### ISSUE TITLE
Documentation misalignment (most probably)

### ISSUE THREAD

**Issue by co-dax** [VahidN/EFCoreSecondLevelCacheInterceptor#230]
# Summary of the issue

The following excerpt from the documentation at the repository home page at [this link](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor?tab=readme-ov-file#does-it-work) 

> Now after running a query multiple times, you should have these logged lines:

> Suppressed result with a TableRows[ee20d2d7-ffc7-4ff9-9484-e8d4eecde53e] from the cache[KeyHash: EB153BD4, CacheDependencies: Page.].
> Using the TableRows[ee20d2d7-ffc7-4ff9-9484-e8d4eecde53e] from the cache.

... is not what I am getting in the debug output.
The only cache related log I am getting is something like: `-- EFCachePolicy --> Absolute|00:51:00|||False`. Below is the screenshot taken from running the official test from the repository itself at the following link [https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12PostgreSql](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12PostgreSql)

![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/7594292/fd3d5be6-6c8d-491e-b417-0bccaf9a1978)

However it does seem that everything is working fine.

 
As a side note, I got an unrelated error when I tried running the test project I mentioned above so I had to add the following line of code `NpgsqlConnection.GlobalTypeMapper.EnableDynamicJson();` as the first line of the `private static void Main(string[] args)` function in Program.cs file.

## Environment

```
.NET (Core) SDK version: 8.0
Microsoft.EntityFrameworkCore version: 8.0
EFCoreSecondLevelCacheInterceptor version: 4.2.0
Database: PostgreSQL
Cache provider: EasyCaching, In-Memory cache, does not matter.
EF Core provider: Npgsql Entity Framework Core provider for PostgreSQL - https://github.com/npgsql/efcore.pg
```

## Example code/Steps to reproduce: 

Official test from the repository itself at the following link [https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12PostgreSql](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/Issues/Issue12PostgreSql)

## Output:

See the screenshot provided above.

**Comment by VahidN** [comment]
`Suppressed result` will happen when a given query is issued multiple times with the exact same SQL commands and same parameter values.

**Comment by co-dax** [comment]
Yes, everything is ok. I just had logging level set to Warning somewhere in the code.

Thanks!
