### ISSUE TITLE
PostgreSQL unsupported data types

### ISSUE THREAD

**Issue by co-dax** [VahidN/EFCoreSecondLevelCacheInterceptor#231]
# Summary of the issue

Should we implement/uncomment some of the converters in the DbContext in the case of PostgreSQL? I am referring to the commented code starting from here [https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/Tests/Issues/Issue12PostgreSql/DataLayer/ApplicationDbContext.cs#L35](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/Tests/Issues/Issue12PostgreSql/DataLayer/ApplicationDbContext.cs#L35)

...I can see this code is not commented for other sql servers like MySql [https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/Tests/Issues/Issue12MySQL/DataLayer/ApplicationDbContext.cs](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/Tests/Issues/Issue12MySQL/DataLayer/ApplicationDbContext.cs)

...but I can also see the `DateOnly` data type (and all other types) is being used successfully in the test project related to PostgreSQL at the following line [https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/Tests/Issues/Issue12PostgreSql/Program.cs#L126](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/Tests/Issues/Issue12PostgreSql/Program.cs#L126)

Thanks.

**Comment by VahidN** [comment]
[These are implemented here.](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/1fbca5c906d5066308b092fbab3a0f3b2c51560d/src/EFCoreSecondLevelCacheInterceptor/EFTableRowsDataReader.cs#L534)

**Comment by co-dax** [comment]
Thanks @VahidN !
