### ISSUE TITLE
Question about recent changes

### ISSUE THREAD

**Issue by Bykiev** [VahidN/EFCoreSecondLevelCacheInterceptor#232]
Hello, thank you for this awesome library!

I'm not sure, but in the recent commit you have changed the logic for getting cache key to this code for .NET 5+
 https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/88271631b7ad4df34da847659e9be9af269dc4e5/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L119

I believe it's ok, but for `DBNull` type (and other nullable reference types) it will return and empty object instead of null and it will lead to different behaviour, maybe it's better to implement a custom converter for System.Text.Json to match the logic for other framework versions?

https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/88271631b7ad4df34da847659e9be9af269dc4e5/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L125

**Comment by VahidN** [comment]
> it will lead to different behaviour

Yes, But it doesn't matter. A new cache entry will be created and used and the old ones will be expired.
