### ISSUE TITLE
Support for FusionCache

### ISSUE THREAD

**Issue by kooshan** [VahidN/EFCoreSecondLevelCacheInterceptor#237]
Thank you for this amazing library. Could you please add support for `FusionCache` provider and drop support for `CacheManager` eventually since that project seems dead?

It would be even better to remove direct dependencies on explicit cache providers and extract them to separate libraries like:
- `EFCoreSecondLevelCacheInterceptor.EasyCaching`
- `EFCoreSecondLevelCacheInterceptor.FusionCache`
- `EFCoreSecondLevelCacheInterceptor.CacheManager`

**Comment by VahidN** [comment]
What else do you want?

**Comment by VahidN** [comment]
You can always write your own cache provider and replace the default one. Just implement the [IEFCacheServiceProvider](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/IEFCacheServiceProvider.cs) and then register it before adding this library this way:
```C#
services.AddSingleton<IEFCacheServiceProvider, MyCustomCacheServiceProvider>();
```

**Comment by kooshan** [comment]
Those were just suggestions. Please calm down!

**Comment by kooshan** [comment]
Thank you!

**Comment by bbehrens** [comment]
😄 Indeed.  Applause to @VahidN!
