### ISSUE TITLE
Requests show up in SQL Server Profiler

### ISSUE THREAD

**Issue by AllanMichaelsen** [VahidN/EFCoreSecondLevelCacheInterceptor#238]
# Summary of the issue
I actually have two questions/issues:
1. I have implemented the MemoryCacheProvider and set it to CacheAllQueries. However it seems that it doesn't work since none of my queries get prefixed with "-- EFCachePolicy --> Sliding|01:00:00|||False". So I had to add it to my RepositoryBase and then the prefix appears.
2. When I run a query the middleware still logs it (as was stated in the documentation it would) but don't see any messages about anything being suppressed. Also every time I run ie. a refresh of my query the query shows up in my SQL Server Profiler, so it would seem that the query doesn't get intercepted and instead is sent to the SQL server.

## Environment
.NET (Core) SDK version: .Net 8
Microsoft.EntityFrameworkCore version: 8.0.4
EFCoreSecondLevelCacheInterceptor version: 4.4.1 
Database: SQL Server 2022
Cache provider: MemoryCacheProvider

## Example code/Steps to reproduce:

In Program.cs
```
builder.Services.AddEFSecondLevelCache(options =>
{
    options
        .UseMemoryCacheProvider()
        .CacheAllQueries(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(60)) // Does not take effect
        .ConfigureLogging(isDevelopment);
});
```
In RepositoryBase
```
var queryable = context
    .Set<T>()
    .Cacheable(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(60)) // This show up in the query
    .AsQueryable();
```

## Output:
![image](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/assets/42305064/5b2b471e-7d39-48be-94e6-d1e78d06e70a)

**Comment by VahidN** [comment]
- When you are using the `CacheAllQueries()`, you don't need to use `Cacheable()` method at all. You can write your normal queries as before and you don't need to pollute your code base with anything else.
- As it's mentioned in the read-me file, [don't forget to add](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor?tab=readme-ov-file#2--add-secondlevelcacheinterceptor-to-your-dbcontextoptionsbuilder-pipeline) the interceptor to the EF-Core's pipeline.

```C#
.AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>()));
```

**Comment by AllanMichaelsen** [comment]
Thanks for swift reply. Great job on the code, love it.

On point 1:At first I didn't add to the query (yes it pollute), but I didn't see the SQL query prefix when using CacheAllQueries. The prefix only shows when using the "pollution".

On point 2: DOOOH... 😂
