### ISSUE TITLE
Redis as an LRU cache?

### ISSUE THREAD

**Issue by emilmuller** [VahidN/EFCoreSecondLevelCacheInterceptor#24]
Hi. Thanks for creating this library!

Instead of absolute and sliding expiration times, would it be possible to support using Redis as an LRU cache? E.g. auto evict data when the memory fills up?

https://redis.io/topics/lru-cache

Kind regards, Emil

**Comment by VahidN** [comment]
You should configure this capability using the `redis.conf` file independently. [more info.](https://github.com/MichaCo/CacheManager/issues/188#issuecomment-323381545)

**Comment by emilmuller** [comment]
@VahidN Does that mean that if I only use Cacheable() without any arguments on a query, and if I have not configured anything in Startup.cs, that it will not set an expiration time, and it will be up to the Redis server when it will evicted?

**Comment by VahidN** [comment]
I have no plan to repeat the read-me file of this library for you. `Cacheable() without any arguments` doesn't mean not setting an expiration time. This is how this library works.
