### ISSUE TITLE
How to set cache key prefix dynamically multi-tenant scenario

### ISSUE THREAD

**Issue by ahmad-kemsan** [VahidN/EFCoreSecondLevelCacheInterceptor#242]
I can see in the example that we can do the following:

```
services.AddEFSecondLevelCache(options =>
    options.UseEasyCachingCoreProvider(
       (serviceProvider, cacheKey) => "redis-db-" + serviceProvider.GetRequiredService<IHttpContextAccesor>().HttpContext.Request.Headers["tenant-id"],
       isHybridCache: false)
    // `Or` you can set the cache key prefix per tenant dynamically  
    .UseCacheKeyPrefix(serviceProvider => "EF_" + serviceProvider.GetRequiredService<IHttpContextAccesor>().HttpContext.Request.Headers["tenant-id"])
    .ConfigureLogging(true)
        // Fallback on db if the caching provider fails.
        .UseDbCallsIfCachingProviderIsDown(TimeSpan.FromMinutes(1))
```
        
But in our case, to get service that returns the tenant-id is scoped, and trying to use that here causes an exception. How do you recommend we solve this problem?

**Comment by VahidN** [comment]
[Follow this thread](https://stackoverflow.com/questions/50200200/net-core-iservicescopefactory-createscope-vs-iserviceprovider-createscope-e)

**Comment by c5racing** [comment]
@ahmad-kemsan, did you ever resolve your issue?  I'm having the same issue.  I don't want to create new scope but rather use the same scope as the caller.

**Comment by VahidN** [comment]
When you have access to the current `HttpContext` via `serviceProvider.GetRequiredService<IHttpContextAccesor>().HttpContext`, it means you have access to the current executing scope and it will give you  access to the request's service container
and its currently instantiated services via  `HttpContext.RequestServices.GetService<IMyService>()`
