### ISSUE TITLE
Support of spatial type

### ISSUE THREAD

**Issue by peterbucher** [VahidN/EFCoreSecondLevelCacheInterceptor#245]
# Summary of the issue
In https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/4#issuecomment-2201327721 was described that some type of support is now there for spatial types. But I dont get whether its not usable or how to use it?

Is spatial type support in some sort usable or not?
If so how to use it? What to change or ignore? I dont get it from the previous ticket.

## Environment

```
.NET (Core) SDK version: 8.0
Microsoft.EntityFrameworkCore version: 8.0
EFCoreSecondLevelCacheInterceptor version: 4.6
Database: SQL Server Express 15.0.2116.2
Cache provider: in-memory
```

## Example code/Steps to reproduce:

use cache with spatial types produces:

`InvalidCastException: Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.`

Stacktrace:

`lambda_method489(Closure , DbDataReader , int[] )
Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord.ReadObject(DbDataReader reader, int ordinal, ReaderColumn column)
Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord.ReadRow()
Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader+BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList<ReaderColumn> columns)
Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(IReadOnlyList<ReaderColumn> columns)
Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+Enumerator.InitializeReader(Enumerator enumerator)
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+Enumerator+<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy+<>c__DisplayClass28_0<TState, TResult>.<Execute>b__0(DbContext context, TState state)
Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation<TState, TResult>(Func<DbContext, TState, ExecutionResult<TResult>> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded, TState state)
Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+Enumerator.MoveNext()
System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
here is some reading from EFCore code`

```

**Comment by VahidN** [comment]
It's not supported and won't be.
