### ISSUE TITLE
[Question] Disable per DbContext?

### ISSUE THREAD

**Issue by CheloXL** [VahidN/EFCoreSecondLevelCacheInterceptor#247]
I have all my queries cached with CacheAllQueries. Now, for a specific usage of my DbContext, I would like to disable any kind of caching. I know I can add a NotCacheable to a dbset, but the idea is not to add those as I want that to be transparent to my original code.

Is there a way to do so? So, basically, disabling all interceptors for that specific DbContext only.

**Comment by VahidN** [comment]
You can specify these type names (DbSet type's of that specific Context) by using [CacheAllQueriesExceptContainingTypes](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor?tab=readme-ov-file#skip-caching-some-of-the-queries-based-on-their-table-names)

**Comment by CheloXL** [comment]
But that's not what I need. I need to disable caching on a complete DbContext. Not on a specific type. 

I have two front-ends: one for the user, one for administrators. On the user front end I want caching enabled. On the administrators, I do not. Stale data in the user front end is ok. On the administration it doesn't, and the database sometimes is updated from outside of my app, so the cache has no way to know that some data is now stale.

That's why I want to disable caching on some dbcontexts and not on others.
