### ISSUE TITLE
Cache not cleared

### ISSUE THREAD

**Issue by wangligen1995** [VahidN/EFCoreSecondLevelCacheInterceptor#25]
# Summary of the issue

I have encountered this situation many times. When I add data and then read it, I cannot read it. I have to manually delete redis cache or wait for the cache to expire before reading it. When I encounter this problem, how can I find out what causes the cache not to be cleared.

## Environment

```
.NET Core SDK version: 
Microsoft.EntityFrameworkCore version: 3.1
EFCoreSecondLevelCacheInterceptor version: 1.5.2
```

## Example code/Steps to reproduce:

```
         var list = _context.Reports_temp.Where(p => p.CreateUserImid == imid).Cacheable(CacheExpirationMode.Sliding, new TimeSpan(0, 10, 0));
```

**Comment by VahidN** [comment]
You can debug it very easily. Set options -> `.DisableLogging(false)` and then follow the `Debug` logs of the library (you should set the minimum log level of your app to `Debug`). It will show you what's going on step by step including the cache invalidation during CRUD operations.
