### ISSUE TITLE
Question about lock

### ISSUE THREAD

**Issue by porya0ras** [VahidN/EFCoreSecondLevelCacheInterceptor#255]
Hello, thank you for this awesome library!

It appears that the locks currently in use cause latency issues when the number of concurrent requests exceeds a certain threshold. Could you please provide an explanation regarding this behavior?
![photo_2024-10-28_11-38-46](https://github.com/user-attachments/assets/a6ef4c8a-b16c-4735-a95e-3337b8440d63)

**Comment by VahidN** [comment]
Well, Actually [it's one the best](https://github.com/MarkCiliaVincenti/AsyncKeyedLock) and performant locking providers available for .NET apps and that lock is required to prevent concurrent access to some non-thread safe resources of the library.
