### ISSUE TITLE
Feature: Execution context

### ISSUE THREAD

**Issue by CheloXL** [VahidN/EFCoreSecondLevelCacheInterceptor#267]
I would like to have some kind of execution context that I can use in my application. My idea is to have an interface that I could register via DI (I want to handle the registration, so I can decide if it will be singleton, scoped, ctor arguments, etc.). The shape of the interface could be something like

```cs
public interface IEFCacheExecutionContext
{
	void BeforeExecution(EFCacheKey cacheKey);
	void AfterExecution(EFCacheKey cacheKey, EFCachedData value, bool fromCache);
}
```

With that interface, you ask to the DI to get its implementation. If none is found, you do nothing. If an implementation is found, you execute the BeforeExecution before you try to get any data, and the AfterExecution once you do anything you have to do (get data from the cache, if none found get from DB, store in cache, etc). The last bool is so I can know if the data was get from the cache or not.

My specific use case is in an asp app, so I can determine if I already have the data (based on the key/hash I would create) and not even send the data to the client asking for it. But I can also use this for other cases that right now I had to solve via some hacks.

I didn't want to make the methods async, but if you think it would be a better idea, maybe you can use a ValueTask as return type (I don't have any async need in those methods, but you never know...)

Do you think something like this is viable? Thanks in advance!

**Comment by VahidN** [comment]
You can use [cacheableEvent](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor?tab=readme-ov-file#does-it-work) for your use-case.

**Comment by CheloXL** [comment]
I don't see how I can access the cache key from that method.

**Comment by VahidN** [comment]
Try the new version. [It has](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheableLogEvent.cs#L28) the EFCacheKey data if it's available at that point (`args.EFCacheKey`).
