### ISSUE TITLE
Question related to invalidation, clarification needed

### ISSUE THREAD

**Issue by zorgoz** [VahidN/EFCoreSecondLevelCacheInterceptor#270]
# Summary of the issue
Related to https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor?tab=readme-ov-file#3--setting-up-the-cache-invalidation

In the given example, the key to invalidate is consisting of the key prefix and the table name. Is this the actual template? I am using Npgsql, where the table names in the generated query are in the format `schema."TableName"`. On one hand, it is weird that each dependent table name has to be prefixed independently, on the other hand fully qualifying the table names seems reasonable to me. And, just to make things worse, `ISqlGenerationHelper.DelimitIdentifier` returns the format from above, while `RelationalEntityTypeExtensions.GetSchemaQualifiedTableName` over `IEntityType` does not include the quotes because it does not rely on the driver.

Please clarify.

**Comment by VahidN** [comment]
[The CacheKey](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L108) is calculated based on the actual query and its related parameters. So ... it doesn't matter how your provider construct that query. It will use the whole part of it. Those prefixes are for multi-tenant scenarios. Also a query can have multiple dependencies (relationships). It will be calculated automatically and you don't need to set or change anything about it.
Also you can always use the `Does it work?!` part[ in the readme](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor?tab=readme-ov-file#does-it-work)  to see what's going on behind the scene.

**Comment by zorgoz** [comment]
So I can confidently specify only the table name when attempting to invalidate an entry even if the same table name is present in multiple schemas?

**Comment by VahidN** [comment]
You don't need to specify anything. You don't need to invalidate anything manually. That scenario was for those who are updating their DB's outside of the DbContext and EF-Core's environment.
