### ISSUE TITLE
Hard dependency on .net core version

### ISSUE THREAD

**Issue by stefandevo** [VahidN/EFCoreSecondLevelCacheInterceptor#272]
# Summary of the issue

I have a need to reference an Entity Framework package that is not updated for .NET 8, meaning I have to downgrade to version 7 of EntityFramework, but my project itself is .net 8.

When adding the package I get the error that's not possible because the package needs .net 8.

---
Is there any way around this problem? Or do I need to fork this package?

**Comment by VahidN** [comment]
> Or do I need to fork this package?

Why didn't you fork `that` package?!

**Comment by VahidN** [comment]
Do whatever you want. Who cares.
