### ISSUE TITLE
Set caching globally for all queries?

### ISSUE THREAD

**Issue by alienwareone** [VahidN/EFCoreSecondLevelCacheInterceptor#3]
Is it possible to set the cache for all queries?

Thanks

**Comment by alienwareone** [comment]
And the reversed method (.NoCacheable) would be nice as well.

It's cool that spatial datatypes can now be cached :). Unlike EF6

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/eec9104efbba5aa62f1e228374bf3f90d0607610
