### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by kindanam** [VahidN/EFCoreSecondLevelCacheInterceptor#30]
# Summary of the issue

Hi, i've followed the steps you describe in the manual.
I've tried both EasyCaching.Core and CacheManager.Core.
Both times I can see the queries using Sql Server Profiler.
There's no exception, nothing going wrong, the queries are marked in the profiler with a tag ("--EFCachePolicy etc...",
but the cache never seems to get hit. Queries always go through.

I probably miss something.
Could you please help ?

## Environment
.net core api using sql server as database
```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.7
```

## Example code/Steps to reproduce:

```
/*
** Startup()
*/
ConfigureCaching(services);
// ...
        private void ConfigureCaching(IServiceCollection services)
        {
            services.AddEFSecondLevelCache(options =>
                options.UseCacheManagerCoreProvider().DisableLogging(true)
            );

            // Add an in-memory cache service provider
            services.AddSingleton(typeof(ICacheManager<>), typeof(BaseCacheManager<>));
            services.AddSingleton(typeof(ICacheManagerConfiguration),
                new CacheManager.Core.ConfigurationBuilder()
                        .WithJsonSerializer()
                        .WithMicrosoftMemoryCacheHandle(instanceName: "MemoryCache1")
                        .Build());
        }

/*
** Usage
*/

        private Task<Dictionary<Guid, Specialties>> GetCachedSpecialties() 
            => _specialtiesRepository
                    .GetAll()
                    .Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromHours(24))
                    .ToDictionaryAsync(s=> s.IdSpecialty);

        private Task<Dictionary<string,ShortDoctorDto>> GetCachedDoctors()
            => _usersService
                    .GetShortDoctors()
                    .Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromHours(1))
                    .ToDictionaryAsync(s=> s.IdUser.ToString().ToLower());
```

## Output:

![image](https://user-images.githubusercontent.com/17311431/80837112-7d61d280-8bf6-11ea-894f-2c2903fb1f0f.png)

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
Those tagged quires [should be intercepted with](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor#2--add-secondlevelcacheinterceptor-to-your-dbcontextoptionsbuilder-pipeline)
```csharp
AddInterceptors(serviceProvider.GetRequiredService<SecondLevelCacheInterceptor>()));
```

**Comment by kindanam** [comment]
ok thank you very much with for the fast reply I'm gonna try now.
I probably missed something in the readme.

**Comment by kindanam** [comment]
It works now!
Thank you very much.
Honestly, the readme file made me think the AddInterceptors line  you gave me was only for people wanting to use their own "custom cache provider".
Maybe it could be clarified a bit ?

**Comment by VahidN** [comment]
well, it's 1,2,3,4 :)
