### ISSUE TITLE
Fails to cache when used with other tags

### ISSUE THREAD

**Issue by RyanThomas73** [VahidN/EFCoreSecondLevelCacheInterceptor#31]
# Fails to cache when used with other tags

The EFCachePolicyParser.getParsedPolicy(..) logic is hard coded to only check the first line of the command text for the policy. 

The `-- EFCachePolicy` tag is not guaranteed to be on the first line, and will fail to parse when used with other `.TagWith(..)` calls on the queryable.

https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/40568d96786586221f33c9a15330da23c545160f/src/EFCoreSecondLevelCacheInterceptor/EFCachePolicyParser.cs#L109

The logic needs to be updated to account for other comments in the command text.

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version:  3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.7.0
```

## Example code/Steps to reproduce:

```
var allPeople = await context.Set<Person>()
    .TagWith("Our custom tags")
    .Cacheable()
    .ToListAsync(cancellationToken)
    .ConfigureAwait(false);
```

## Output:

```
Exception message: N/A
Full Stack trace: N/A
```

**Comment by VahidN** [comment]
Thank you. Added it.
