### ISSUE TITLE
Cache Policy Tag Performance Improvements

### ISSUE THREAD

**Issue by RyanThomas73** [VahidN/EFCoreSecondLevelCacheInterceptor#33]
# Cache Policy Tag Performance Improvements

Currently the second level cache interceptor leaves the `-- EFCachPolicy` tag in the executed sql. This has performance drawbacks that could be mitigated by a number of approaches. 

For db providers that use query plan caching, the differences in the comments will cause failures to re-use existing query plans from the query plan cache. The comments also unnecessarily increase the size of the sql that needs to be sent.

Improvements:
1. Remove the `CallerLineNumber` and `CallerMemberName` properties from the cache policy / cache policy tag. These properties are not referenced/used anywhere other than the `ToString()` method and are unnecessary. Removing these, particularly the line number, will eliminate query plan cache misses caused by the query coming from a different source code line.

2. Remove the cache policy query tag from the command text in the `ProcessExecutingCommands(..) ` method before continuing. The cache policy is parsed from this tag in these methods (e.g. `ReaderExecutingAsync`). 

The parsed cache policy object can be held on to. For example a concurrent dictionary could be used with the `DbCommand` as the key and the `EFCachePolicy` object as the value. The tag can be removed from the command text. The `ProcessExecutedCommands(..)` methods can retrieve the parsed `EFCachePolicy` object from the dictionary and do not need the cache policy string to be parsed again.

Eliminating the comment from the executed sql will reduce the sql payload that needs to be sent and will eliminate query plan cache misses that would occur when the call site or cache policy properties are different from a previous query.

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.3
EFCoreSecondLevelCacheInterceptor version: 1.7.0
```

## Example code/Steps to reproduce:

```
public T ProcessExecutingCommands<T>(DbCommand command, DbContext context, T result, [CallerMemberName] string methodName = null)
{
    var cachePolicy = _cachePolicyParser.GetEFCachePolicy(command.CommandText);
    if (cachePolicy != null)
    {
        if (_cachePolicyLookup.TryAdd(comand, cachePolicy)
        {
            command.CommandText = _cachePolicyParser.RemoveEFCachePolicyTag(command.CommandText);
        }
```

## Output:

```
Exception message: N/A
Full Stack trace: N/A
```

**Comment by RyanThomas73** [comment]
I'll submit a PR for this in a little bit as well

**Comment by VahidN** [comment]
No. Please don't send it. This is what it is! I want to see those numbers and lines in the logs. Also this is just one query and let the DB cache it again. I don't care if it's a miss for the 1st time.

**Comment by RyanThomas73** [comment]
I can make it a configurable option so that it can be turned on / off.
