### ISSUE TITLE
Possibility of caching as dictionary or list

### ISSUE THREAD

**Issue by kindanam** [VahidN/EFCoreSecondLevelCacheInterceptor#36]
# Summary of the issue

Hi, I've started using this library and I like it.
I have a question though.
If I'm not mistaken, it seems that only the result of the query is put in cache, which means that the real result of the linq query chain, often ending with ToDictionary(), ToList() is not put in cache.
And the creation of this structure can be expensive.
Would it be possible to include in the library something like AsCacheableDictionary(Async), AsCacheableList(Async), maybe also by prefixing the cachekey with the resulting type ?
Or do you think it's completely irrelevant and in that case, do you have an idea on how to achieve this ?

Thanks in advance,
Kindanam

## Environment

```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1 
EFCoreSecondLevelCacheInterceptor version: 1.7.1 
```

## Example code/Steps to reproduce:

```
var myDictionary = await myQuery.Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromHours(1)).ToDictionaryAsync(myEntity => myEntity.Key);

// The hash code is different each time. it seems that the dictionary is always recreated and not itself put in cache
var hash = myDictionary.GetHashCode();
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
- This library works on the DataReader level of EF. It has not access to anything else.
- Also it's performance is good:
![Performance](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.PerformanceTests/int-pref.png)

**Comment by jasenf** [comment]
This actually seems like a really interesting idea and could potentially provide even better performance improvements.   I think @kindamam was trying to discuss how we store the final result set in the cache, not the key.    If we know that a certain result will always be used as a List<T> or Dictionary, etc.   Storing the result in that set would save a ton of time by preventing us from re-composing the native result set into the data-structure.

Maybe something like .AsCachableList<T>() would be a great first start?  Not sure of the complexity for doing this, but it is a great idea.

**Comment by kindanam** [comment]
> This actually seems like a really interesting idea and could potentially provide even better performance improvements. I think @kindamam was trying to discuss how we store the final result set in the cache, not the key. If we know that a certain result will always be used as a List or Dictionary, etc. Storing the result in that set would save a ton of time by preventing us from re-composing the native result set into the data-structure.
> 
> Maybe something like .AsCachableList() would be a great first start? Not sure of the complexity for doing this, but it is a great idea.

Thanks @jasenf . It's exactly what I was thinking about.
I know from experience that the recreation of dictionaries in some contexts, can easily have a significant cost. 
In the context I was talking about, we had 100 req per sec, and we were creating dictionaries with 3500 keys.
Does not seem very big, but we saw those dictionaries clearly in our memory dumps in Production (because obviously these dictionaries were only a small part of each request, and should have been taken from cache as a reference to the same dictionary instance, and not cloning it for no reason at every request)

I'm really interested in this feature, so I hope you'll be interested too, and will find a way to implement it.
Thanks, Kindanam
