### ISSUE TITLE
سوال در مورد FromSqlRaw 

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/EFCoreSecondLevelCacheInterceptor#37]
<div dir="rtl">

سلام وقت بخیر
من برای کش کردن خروجی از SqlRaw استفاده میکنم بدون مشکل کار میکنه
فقط بخش خروجی که در SP مشخص میشه مثل StatusCode اولین بار درست نمایش میده اما دفعات بعدی مقدار صفر نمایش میده اما اطلاعات رو از کش میخونه
آیا راهی هست که بخش Output در SP رو کش کنه؟ یا اصلا در این جور موارد نباید کش کرد؟

**Comment by VahidN** [comment]
Why did you change the format of this issue? Why did you remove the how to reporduce it?
