### ISSUE TITLE
Clarification of usage on IQueryable

### ISSUE THREAD

**Issue by superman-lopez** [VahidN/EFCoreSecondLevelCacheInterceptor#38]
I am considering to use this library, but I would like to understand how to use it effectively.  In the examples the queries are immediately executed, as it calls `.FirstOrDefault`.  However I often use `IQueryable` and would like to understand at what point the data is cached.

for example:
``` c
IQueryable query = context.Cities.AsQueryable().AsNoTracking();
if (queryObj.name)
	query = query.Where(c => c.Name.Contains(queryObj.name));
// more filters can be applied on `query` depending on the values in `queryObj`
```
Then later on I will call the `IQueryable` with something like `List<City> result =  await query.ToListAsync()`. Would I put `Cacheable()` on the call with `AsQueryable` or `ToList`?  And what would be cached, the complete DbSet `Cities`, the results filtered for the specific value in `queryObj.string`, or maybe nothing at all because the query is different every time for new values in the multiple properties of `queryObj`?

**Comment by VahidN** [comment]
- The result of the whole expression tree will be cached, if it's marked as `Cachable()`, when it's materialized (calling .ToList, .FirstOrDefault, etc).
- If you are chaining different parts of the query, put the `Cachable()` before the materialization part.
- Having different parameter values, different final produced SQL will create a new cache-key. [more info](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCacheKeyProvider.cs#L66).
