### ISSUE TITLE
Support for spatial type

### ISSUE THREAD

**Issue by alienwareone** [VahidN/EFCoreSecondLevelCacheInterceptor#4]
I thought EF Core does the conversion for Spatial Type itself before EfCache gets its value...
> InvalidCastException: Unable to cast object of type 'Microsoft.SqlServer.Types.SqlGeography' to type 'Microsoft.Data.SqlClient.Server.IBinarySerialize'.

Relevant Stacktrace:
```
Microsoft.Data.SqlClient.Server.BinarySerializeSerializer.Deserialize(Stream s)
Microsoft.Data.SqlClient.Server.SerializationHelperSql9.Deserialize(Stream s, Type resultType)
Microsoft.Data.SqlClient.SqlConnection.GetUdtValue(object value, SqlMetaDataPriv metaData, bool returnDBNull)
Microsoft.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)
Microsoft.Data.SqlClient.SqlDataReader.GetValues(object[] values)
EFCoreSecondLevelCacheInterceptor.EFDataReaderLoader.Read()
EFCoreSecondLevelCacheInterceptor.EFDataReaderLoader.LoadAndClose()
```

**Comment by VahidN** [comment]
Please provide (attach/drag & drop) a simple console sample about this issue.

**Comment by alienwareone** [comment]
I played around with your source code to skip the spatial datatype column but it seems that EF internally tries to convert back to SqlDataReader :/
`InvalidCastException: Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.`
https://github.com/alienwareone/EFCoreSecondLevelCacheInterceptorSpatial

**Comment by VahidN** [comment]
I added [binary-data](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFDataReaderLoader.cs#L269) support. It only works with the [Microsoft.SqlServer.Types](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue4SpatialType/Issue4SpatialType.csproj#L21) package. But ... [there are things that I can't change](https://github.com/dotnet/SqlClient/issues/465).

**Comment by peterbucher** [comment]
> I added [binary-data](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFDataReaderLoader.cs#L269) support. It only works with the [Microsoft.SqlServer.Types](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue4SpatialType/Issue4SpatialType.csproj#L21) package. But ... [there are things that I can't change](https://github.com/dotnet/SqlClient/issues/465).

Hi, what does that mean "added binary-data"?
The error 

"InvalidCastException: Unable to cast object of type 'EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'."

is occouring on me with version 4.5.0 and the SqlServer.Types are in version 160.1000.6.

What could I do to get rid of the erro and getting that to work?

Its a super project and speeds my application up!
For now I have deactivated the caching but it would be wonderful if it would work together.


Regards Peter

**Comment by peterbucher** [comment]
Hi

I tried how to use that SqServer.Types. But I am stuck with these two types - of which are not seen as "isBinary" as the other twos..

They are the same and it makes it in EFCore like this:
`        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Point>(
                name: "Location",
                table: "Spots",
                type: "geography",
                nullable: true);
        }`

Thanks in advance!
