### ISSUE TITLE
Question? - Testing for cache hit

### ISSUE THREAD

**Issue by aday12345** [VahidN/EFCoreSecondLevelCacheInterceptor#40]
is it possible to test  after the query was run if the data came from the database or the cache?

**Comment by VahidN** [comment]
Yes. Follow [the test project](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/tree/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests) or use a profiler like the [SQL Server Profiler](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/27#issuecomment-618443494).
