### ISSUE TITLE
Cache Only This Specific Entities List

### ISSUE THREAD

**Issue by Fabrizio86** [VahidN/EFCoreSecondLevelCacheInterceptor#41]
# Summary of the issue
Hi we are currently exploring the possibility to incorporate this library into our project, one scenario that came up,
due to the large query base, is the capability to specify a list of "cache this only" (e.g.: { "dbo.Entity1", "dbo.Entity2", ...})

 so in combination with "cache all queries" configuration enabled, the interceptor would filter out all the other entities, rather than have to modify every single query manually(over 300+) to add .Cacheable()

Another reason why we would need something like this, we have implemented our entities hidden behind interfaces (the interceptor is DI passed with Autofac) and in a separated project from the main application in their own library, so adding the .Cacheable(), would cause the caching logic to leak in the context and potentially making the maintainability a nightmare in the future.

If this is actually already implemented please let me know cause I couldn't find it in the system

## Environment

```
.NET Core SDK version: .Net Standard 2.1
Microsoft.EntityFrameworkCore version: 3.1.5
EFCoreSecondLevelCacheInterceptor version: 
```

**Comment by VahidN** [comment]
Added it via#https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/b03d818094aea9b67f912cc343f2792f2771efb3
