### ISSUE TITLE
cache all query doesnt work

### ISSUE THREAD

**Issue by mmokhtari** [VahidN/EFCoreSecondLevelCacheInterceptor#45]
hi
im config like this

      services.AddEFSecondLevelCache(options =>
            {
                options.UseMemoryCacheProvider(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(30))
                    .DisableLogging(false)
                    .CacheAllQueries(CacheExpirationMode.Sliding, TimeSpan.FromMinutes(30));
            });

but it doesnt cache my queries im tracing with sql profile im faceing db request

when i use use the cacheable() for mu queries this neither doest work and have db request
but this "-- EFCachePolicy --> Absolute|00:30:00|||True" is apearing in queries

**Comment by VahidN** [comment]
It doesn't work for you in cache all queries mode.
It doesn't work for you in cache one query mode.
Fine! Don't use it. Thank you.
