### ISSUE TITLE
Clarification requested on invalidation

### ISSUE THREAD

**Issue by superman-lopez** [VahidN/EFCoreSecondLevelCacheInterceptor#47]
From the readme:
>Invalidation
>
>This cache is updated when an entity is changed (insert, update, or delete) via a DbContext that uses this library. If the database is updated through some other means, such as a stored procedure or trigger, the cache becomes stale.

I expect that the cache is updated when an entity is changed in the _relevant_ `DbSet`.  Is that correct?  Or are all caches invalidated when _any_ entity has been touched?

**Comment by VahidN** [comment]
>  Is that correct?

Yes. From the final SQL query -> Extracts the real in use table_name's from it -> To create the `cache dependencies`. Then after each CRUD operations these related `dependencies` will be invalidated.

**Comment by VahidN** [comment]
>  Is that correct?

Yes. From the final SQL query -> Extracts the real in use table_name's from it -> To create the `cache dependencies`. Then after each CRUD operations these related `dependencies` will be invalidated.
