### ISSUE TITLE
muliple app use same context

### ISSUE THREAD

**Issue by MEnzio** [VahidN/EFCoreSecondLevelCacheInterceptor#48]
hello there

thank u for ur incredible project

i have two separate application use same shared context

is there any way when the first app invalidate the cache the second app do it as well?

i will be thankfull if u help me

**Comment by VahidN** [comment]
You should use a distributed cache such as **_Redis_**. If app-1 invalidates the cache, app-2 will be forced to read the new data from the database, and cache it again in the Redis DB.
