### ISSUE TITLE
Support for Net5.0

### ISSUE THREAD

**Issue by kooshan** [VahidN/EFCoreSecondLevelCacheInterceptor#49]
Hi,
This is more of a question than an issue.
With release of Net5.0 RC1 we are planning to do an upgrade. Is this package already compatible with Net5.0 and EFCore5.0 as it is right now?

**Comment by kooshan** [comment]
In particular, when `PublishReadyToRun` is set to `True` in csproj file, the following compile error is thrown:
```
 Error compiling C:\...\.nuget\packages\efseco
ndlevelcache.core\2.9.1\lib\netstandard2.0\EFSecondLevelCache.Core.dll: Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' from assembly 'Microsoft.
EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```
turning that flag off would proceed with normal compilation.

**Comment by VahidN** [comment]
Added .NET 5.0-rc2 support via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/8a4eb97ad177311a81f653a73b4ac68cd8244b25
