### ISSUE TITLE
پاک کردن کش به صورت دستی

### ISSUE THREAD

**Issue by rbsdotnet** [VahidN/EFCoreSecondLevelCacheInterceptor#5]
<div dir="rtl">

جناب نصیری در حالت استفاده از memory cache به چه شکل میشه کش رو به صورت دستی خالی کرد؟

**Comment by VahidN** [comment]
To clear the whole cache manually, inject the `IEFCacheServiceProvider` service and then call its `ClearAllCachedEntries()` method.
