### ISSUE TITLE
Support .NET Core 3.1

### ISSUE THREAD

**Issue by arashaan** [VahidN/EFCoreSecondLevelCacheInterceptor#50]
# Summary of the issue

It's seems .NET Core 3.1 no longer been supported, right ?
Unable to update to v.1.9.1 in NUGET !

## Environment

```
.NET Core SDK version: 
Microsoft.EntityFrameworkCore version: 3.1.9
EFCoreSecondLevelCacheInterceptor version: 1.9.0
```

```
Exception message: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Microsoft.EntityFrameworkCore from 5.0.0-rc.2.20475.6 to 3.1.9. Reference the package directly from the project to select a different version. 
 R8.Lib.EntityFrameworkCore -> EFCoreSecondLevelCacheInterceptor 1.9.1 -> Microsoft.EntityFrameworkCore (>= 5.0.0-rc.2.20475.6) 
 R8.Lib.EntityFrameworkCore -> Microsoft.EntityFrameworkCore (>= 3.1.9)	R8.Lib.EntityFrameworkCore	E:\Work\Develope\Asp\Ecohos\R8.Lib.EntityFrameworkCore\R8.Lib.EntityFrameworkCore.csproj	1	

Full Stack trace:
```

**Comment by VahidN** [comment]
`It's seems .NET Core 3.1 no longer been supported, right ?`

No.
If the `TargetFramework` of your project is `netstandard2.0` or `net461`, EF Core 3.1 will be used. If the `TargetFramework` of your project is `net5.0` or `netstandard2.1`, EF Core 5x will be used.

**Comment by arashaan** [comment]
Sorry, currently I use `Asp.NET Core 3.1`. i wrote `.NET Core 3.1` by mistake...
What you think about this ?

**Comment by VahidN** [comment]
What's the `TargetFramework` of your `R8.Lib.EntityFrameworkCore` project?

**Comment by arashaan** [comment]
> Sorry, currently I use `Asp.NET Core 3.1`. i wrote `.NET Core 3.1` by mistake...

I didn't want to make confliction between `.NET Core` for `Windows` and `.Net Core` for `Asp Core`

I mean, I use `Asp Core`. and `<TargetFramework>netcoreapp3.1</TargetFramework>`

But, I hadn't problem every time I updated your library.
But now, I don't know exactly what is the problem.

Maybe the problem is about the minimum version you set for dependencies ( .NET CORE 5 and EF CORE 5 )

**Dependencies**
```  
.NETCoreApp,Version=v5.0
     Microsoft.EntityFrameworkCore (>= 5.0.0-rc.2.20475.6)
     Microsoft.EntityFrameworkCore.Relational (>= 5.0.0-rc.2.20475.6) 
```

**Comment by VahidN** [comment]
Try version 1.9.2. [I added](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/df3e9c052f955fa7fb1cdf64530b1e0d6365c809#diff-13b25a79c5482e9f3bd1229817d2cb932f6de8f87f0edb49d570e4a39f2f68bcR6) `netcoreapp3.1` to the list of supported TargetFrameworks.

**Comment by arashaan** [comment]
Thanks a lot. Now works like a charm ⭐
