### ISSUE TITLE
The nuget package for .NETStandard, Version 2.1 has dependency on Microsoft.EntityFrameworkCore on 5.0.0-rc.2.20475.6 instead of 3.1.6.

### ISSUE THREAD

**Issue by valentinmarinro** [VahidN/EFCoreSecondLevelCacheInterceptor#52]
# Summary of the issue

The nuget package for .NETStandard, Version 2.1 has dependency on Microsoft.EntityFrameworkCore on 5.0.0-rc.2.20475.6 instead of 3.1.6.

## Environment

```
.NET Core SDK version: .NETStandard v2.1
Microsoft.EntityFrameworkCore version: 3.1.6
EFCoreSecondLevelCacheInterceptor version: 2.0.0
```

## Example code/Steps to reproduce:
Try to install EFCoreSecondLevelCacheInterceptor in a .NETStandard v2.1 library

```
Exception message:
Full Stack trace:
```
Detected package downgrade: Microsoft.EntityFrameworkCore from 5.0.0-rc.2.20475.6 to 3.1.6. Reference the package directly from the project to select a different version. 
EFCoreSecondLevelCacheInterceptor 2.0.0 -> Microsoft.EntityFrameworkCore (>= 5.0.0-rc.2.20475.6)

**Comment by VahidN** [comment]
[It's discussed here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/50).

**Comment by valentinmarinro** [comment]
Understand, but to use EFCoreSecondLevelCacheInterceptor 2.0.0 in a .NETStandard v2.1 I'm required to upgrade the EF Core version from 3.1 to 5.0 which I'm not allowed to do

**Comment by VahidN** [comment]
These are EF-Core's team decisions, not mine. If you are using `.NETStandard 2.1`, when its(EF-Core 5x) final version is available, you will be forced to use the EF-Core on the first NuGet packages update.
- [EF-Core 3.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/3.1.9) is based on `.NETStandard 2.0`.
- EF-Core 5x is based on `.NETStandard 2.1`.
Library authors have no other choice here.
