### ISSUE TITLE
Adding prefix before the instance name for Redis

### ISSUE THREAD

**Issue by Rana182** [VahidN/EFCoreSecondLevelCacheInterceptor#53]
# Summary of the issue

I am working on multiple projects with multiple databases and I would like to know if it's possible to add a prefix specifying the project's name to make it easier for me to delete entries from Cache belonging to a specific project.

Microsoft.EntityFrameworkCore version: 3.1

**Comment by VahidN** [comment]
>  if it's possible to add a prefix 

No. Just don't use it. Thanks.
