### ISSUE TITLE
.Net 3.1 & .Net Standard 2.1

### ISSUE THREAD

**Issue by twurm** [VahidN/EFCoreSecondLevelCacheInterceptor#56]
# Summary of the issue
We currently use the old version of your second level cache.  While in the process of upgrading to this version we ran into an issue with netstandard2.1 and .Net Core 3.1.  With .Net 5 not being a LTS release we need to stay on .Net 3.1.  That doesn't seem possible because we are also using netstandard2.1.  The issue seems to be related to the following:

``` xml
<ItemGroup Condition="('$(TargetFramework)' == 'net5.0') or  ('$(TargetFramework)' == 'netstandard2.1')">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0" />
    <PackageReference Include="CacheManager.Core" Version="1.2.0" />
    <PackageReference Include="EasyCaching.Core" Version="0.9.0" />
</ItemGroup>
```

## Environment

```
.NET Core SDK version: 3.1.400
Microsoft.EntityFrameworkCore version: 3.1.10
EFCoreSecondLevelCacheInterceptor version: 2.0.1
```

## Example code/Steps to reproduce:

``` xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageId>Any.Package</PackageId>
    <Authors>e-Ventus Corporation</Authors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>library</OutputType>
    <DocumentationFile>bin\Debug\netstandard2.0\Any.Package.xml</DocumentationFile>
    <NoWarn>1701;1702;1705;1591</NoWarn>
    <CodeAnalysisRuleSet>Any.Package.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet>Any.Package.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EasyCaching.InMemory" Version="0.9.0" />
    <PackageReference Include="EFCoreSecondLevelCacheInterceptor" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.10" />
    <PackageReference Include="System.Composition" Version="1.4.1" />
  </ItemGroup>
</Project>
```

## Output:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Microsoft.EntityFrameworkCore from 5.0.0 to 3.1.10. Reference the package directly from the project to select a different version. 
 Any.Package -> EFCoreSecondLevelCacheInterceptor 2.0.1 -> Microsoft.EntityFrameworkCore (>= 5.0.0) 
 Any.Package -> Microsoft.EntityFrameworkCore (>= 3.1.10)	Any.Package	D:\Source\Repos\Any\src\Any.Package\Any.Package.csproj	1	
```

**Comment by VahidN** [comment]
It's discussed [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/52) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/50).

**Comment by twurm** [comment]
@VahidN thanks for the reference material.  I read through and still don't fully understand.  Microsoft's own documentation suggests that you should use netstandard2.1 if targeting .Net 3.1.x.  So I'm still a little confused.

## .NET Standard not deprecated
.NET Standard is still needed for libraries that can be used by multiple .NET implementations. We recommend you target .NET Standard in the following scenarios:

- Use netstandard2.0 to share code between .NET Framework and all other implementations of .NET.
- Use netstandard2.1 to share code between Mono, Xamarin, and .NET Core 3.x.

Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-standard-not-deprecated

**Comment by VahidN** [comment]
EF-Core 5x is based on [netstandard2.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0) (look at its Dependencies). Which means if you update your NuGet packages right now, you will get the V5x automatically. So If you want to stay on .NET Core 3x, you should switch to netstandard2.0.

**Comment by twurm** [comment]
@VahidN thanks again for the quick response.  I looked at the dependencies when looking at the two tickets you mentioned.  I'm still missing something and for that I am sorry.  Changing the project to target: ```<TargetFramework>netstandard2.0</TargetFramework>``` instead ```<TargetFramework>netstandard2.1</TargetFramework>``` of  doesn't change the suggested Microsoft.EntityFrameworkCore version.  It still wants you to install 5.0.0 so I don't see the correlation there.  

I understand that they changed the dependencies to use netstandard2_1 but I was under the impression that was more about API scope than anything and feature sets.  We have things in our project that use the API's exposed as part of netstandard2_1 so downgrading isn't really an option.  I understand if there isn't anything you can do.

**Comment by VahidN** [comment]
Run these commands from the root of your solution to see what are the available EF-Core versions for your entire solution:
```
dotnet restore
dotnet tool update --global dotnet-outdated-tool
dotnet outdated 
```

**Comment by twurm** [comment]
Here is the results for one of our root packages that introduce EF Core.  I can it both as netstandard2.0 and netstandard2.1.

#### netstandard2.0
Mx.Core
  [.NETStandard,Version=v2.0]
  FluentValidation                                                               8.6.2  -> 9.3.0
  Microsoft.EntityFrameworkCore                                      3.1.10 -> 5.0.0
  Microsoft.EntityFrameworkCore.SqlServer                      3.1.10 -> 5.0.0
  Microsoft.Extensions.Configuration.Json                         3.1.10 -> 5.0.0
  Microsoft.Extensions.Options.ConfigurationExtensions  3.1.10 -> 5.0.0
  System.Composition                                                       1.4.1  -> 5.0.0

#### netstandard2.1
Mx.Core
  [.NETStandard,Version=v2.1]
  FluentValidation                                                               8.6.2  -> 9.3.0
  Microsoft.EntityFrameworkCore                                      3.1.10 -> 5.0.0
  Microsoft.EntityFrameworkCore.SqlServer                      3.1.10 -> 5.0.0
  Microsoft.Extensions.Configuration.Json                         3.1.10 -> 5.0.0
  Microsoft.Extensions.Options.ConfigurationExtensions  3.1.10 -> 5.0.0
  System.Composition                                                        1.4.1  -> 5.0.0

**Comment by VahidN** [comment]
Yes. As you see if you update all of your `netstandard2.1` project's dependencies automatically to their latest versions, you will have the EF-Core 5x by default and If you use `netstandard2.0` for it, EF-Core won't be touched.

**Comment by twurm** [comment]
Well seems like Microsoft has made a mess honestly.  We can't jump to .Net 5 due to its support policy and we can't fall back to netstandard2.0 due to the API's in netstandard2.1 we are using.

**Comment by twurm** [comment]
@VahidN one more thing to add to the confusion, there seems to be mixed messages coming from the EF Core team: [https://github.com/dotnet/efcore/issues/23223#issuecomment-723418557](https://github.com/dotnet/efcore/issues/23223#issuecomment-723418557)
