### ISSUE TITLE
Redis DefaultDataBase

### ISSUE THREAD

**Issue by pht123** [VahidN/EFCoreSecondLevelCacheInterceptor#6]
class: RedisDbCache
Method:  **clearItems**(string pattern = "")
var keys = string.IsNullOrWhiteSpace(pattern) ? server.Keys() : server.Keys(pattern: $"*{pattern}*");

if(DefaultDataBase != 0)  can not get keys
Unable to enter  **foreach (var key in keys)** 

**Here is the correct example**
var keys = string.IsNullOrWhiteSpace(pattern) ? server.Keys(_connection.GetDatabase().Database) : server.Keys(_connection.GetDatabase().Database, pattern: $"*{pattern}*");

**Comment by VahidN** [comment]
Thanks. Fixed it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/d681b2bec2177c5d33e9982329e19ce2f73ad717
