### ISSUE TITLE
Unable to cast object of type 'System.Int16' to type 'System.Boolean'

### ISSUE THREAD

**Issue by Aleksaas** [VahidN/EFCoreSecondLevelCacheInterceptor#60]
# Summary of the issue
Error: Unable to cast object of type 'System.Int16' to type 'System.Boolean'
Database: Oracle, Driver: Oracle.EntityFrameworkCore
Note: It works with SQL Server

## Environment

```
.NET Core SDK version: 
Microsoft.EntityFrameworkCore version: 3.1
EFCoreSecondLevelCacheInterceptor version: 1.5.1.0
```

## Example code/Steps to reproduce:
Need to have boolean property on entity.

## Output:

Exception message:
Full Stack trace:
```
System.InvalidCastException: Unable to cast object of type 'System.Int16' to type 'System.Boolean'.
   at EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetBoolean(Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Comment by VahidN** [comment]
V 1.5.1? The [last version](https://www.nuget.org/packages/EFCoreSecondLevelCacheInterceptor/) is 2.1 and [it can try](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFTableRowsDataReader.cs#L153) to convert these issues.
