### ISSUE TITLE
Postgres Database connection is still opened when using Redis

### ISSUE THREAD

**Issue by faizan-kamili** [VahidN/EFCoreSecondLevelCacheInterceptor#61]
# Summary of the issue

We were doing some load testing to see the performance gain from using this library.

We sent out 10,000 API requests and only the first query was sent to Postgres and the rest 9,999 were returned by Redis as expected. 

But surprisingly we kept on getting crashes from Postgres library that connection limit has reached even though Redis was serving the requests. 

So it turned out that this library opens the Postgres connection, gets data from Redis, and closes the Postgres connection.

Can you confirm this behaviour is intended?

## Environment
```
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.10
EFCoreSecondLevelCacheInterceptor version: 2.0.1
```

**Comment by VahidN** [comment]
> So it turned out that this library opens the Postgres connection, gets data from Redis, and closes the Postgres connection.

This is an open source project and [here is the core of this library](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/DbCommandInterceptorProcessor.cs). There is nothing more to it and doesn't control the connections or anything else and .... it seems the Postgres provider has a lot of issues. So it's better to ask them not here.
