### ISSUE TITLE
Prevent Caching of queries containing NOW()

### ISSUE THREAD

**Issue by ahmad-kemsan** [VahidN/EFCoreSecondLevelCacheInterceptor#62]
# Summary of the issue
We are encountering an issue wherein the queries having NOW() are getting cached for example:

`SELECT p."AppVersion", p."CreatedAt", p."ExpiresAt" FROM "Products" AS p WHERE ( p."ExpiresAt" > NOW() AT TIME ZONE 'UTC')`

This query can return a different result based on the value of NOW() hence, this should not be cached. Can you please help us with this?

## Environment
.NET Core SDK version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.10
EFCoreSecondLevelCacheInterceptor version: 2.1.0
```

**Comment by VahidN** [comment]
Try V 2.2.0.
