### ISSUE TITLE
Datetime type fields get less than milliseconds

### ISSUE THREAD

**Issue by 2693252993** [VahidN/EFCoreSecondLevelCacheInterceptor#63]
# Summary of the issue
Hello, I used the global cache，Using the built-in In-Memory cache provider, but the datetime type obtained by the query was less than milliseconds, so I could normally get milliseconds by adding NotCacheable to the query。
## Environment

```
.NET Core SDK version: 
Microsoft.EntityFrameworkCore version: 3.1
EFCoreSecondLevelCacheInterceptor version: 2.0
```

**Comment by VahidN** [comment]
- [I can't reproduce it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/EFCoreSecondLevelCacheInterceptor.Tests/SecondLevelCacheInterceptorBasicTests.cs#L471).
- The built-in In-Memory cache provider [doesn't change the cached object](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L26).
- Probably you have [this issue](https://stackoverflow.com/a/23788730/298573).
- Also make sure your DB supports `milliseconds` and choose an appropriate `data type` for it.

**Comment by 2693252993** [comment]
@RyanThomas73 
My Init
![image](https://user-images.githubusercontent.com/27254047/103253077-a7080f00-49ba-11eb-9740-2f22ba70ddb8.png)
![image](https://user-images.githubusercontent.com/27254047/103253094-b8511b80-49ba-11eb-9f7c-25ad8fc64b82.png)
My Code
![image](https://user-images.githubusercontent.com/27254047/103253112-c56e0a80-49ba-11eb-8ed3-f224325466a3.png)
Field definition
![image](https://user-images.githubusercontent.com/27254047/103253155-ecc4d780-49ba-11eb-8bfa-dff912d70382.png)
Print
![image](https://user-images.githubusercontent.com/27254047/103253196-1a118580-49bb-11eb-8237-1bd7e6f278bd.png)
My DB
![image](https://user-images.githubusercontent.com/27254047/103253245-51803200-49bb-11eb-845e-7d8dc74ca46c.png)
