### ISSUE TITLE
Adding DbConnectionIntercepter to prevent opening DB connections

### ISSUE THREAD

**Issue by ahmad-kemsan** [VahidN/EFCoreSecondLevelCacheInterceptor#65]
We were doing some testing of your library and we figured out that the DB connection is always opened even if the results are received from the cache.

This has a performance impact and decreases the throughput when a very high throughput can be achieved when using your library. In our heavy load testing, for a real scenario, the throughput actually decreased when we used your library which should not happen. So, I suspect this DB connection opening is causing the issue. 

I went through your code and you are using DbCommandInterceptor and nowhere I could find DbConnectionIntercepter. I suggest you should use this interceptor too, to prevent the connection from opening if the data is present in the cache.

**Comment by VahidN** [comment]
It's not doable. First a connection will be made and then a command will be created. Which means it's not possible to know the connection X is related to the command Y at the beginning and stop it if the result of the command Y has been cached before. There is no relation between a connectinID and a commandID. Plus a connection can be used to run multiple commands. Also if we suppress a connection at the interceptors level, next levels will be canceled too.
