### ISSUE TITLE
How to query database directly instead of reporting errors when redis is abnormal

### ISSUE THREAD

**Issue by wangligen1995** [VahidN/EFCoreSecondLevelCacheInterceptor#7]
I have a question ,when my redis is error ，the query returns the result of an exception,How to configure to avoid this

**Comment by VahidN** [comment]
Should a low level library catch exceptions and suppress them? No.  crashes and excretions are very good things. they will help you to understand something is wrong and upper level layers should catch them or don't. when an app is not able to connect to a backend, it should crash and there is nothing wrong with it. If a person is sick and doesn't feel any symptoms (suppressed crashes / excretions), that person will die sooner than expected.
