### ISSUE TITLE
Still send request to DB with cacheable query for Cosmos DB

### ISSUE THREAD

**Issue by hmqgg** [VahidN/EFCoreSecondLevelCacheInterceptor#8]
# Summary of the issue
I tried Cacheable and CacheAllQueries, with Absolute and Sliding expiration, but all the queries still send requests to DB.

Tracked by VS2019 debugger, the logger showed every query sent the request to DocDB.

## Environment

```
.NET Core SDK version: 3.1.200
Microsoft.EntityFrameworkCore version: 3.1.2
EFCoreSecondLevelCacheInterceptor version: 1.1.2
DB: Azure Cosmos DB Emulator
```

## Example code/Steps to reproduce:

```
optionsBuilder.UseCosmos(xxx, xxx, xxx);
optionsBuilder.AddInterceptors(new SecondLevelCacheInterceptor());
...
services.AddEFSecondLevelCache(opts => opts.UseMemoryCacheProvider());
...
var user = await context.Users
.Cacheable(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(10))
.FirstOrDefaultAsync(u => u.UserId == userId);
```

## Output:
DocDB trace etc.

**Comment by VahidN** [comment]
Never tested with Cosmos DB.

**Comment by rbt-eugene** [comment]
Verified also that Cosmos DB requests are not cached.

Did some debugging and looks like the Interceptors are not triggered.
