### ISSUE TITLE
Is there a possibility to not cache a empty/null result of a Query?

### ISSUE THREAD

**Issue by NicoKno** [VahidN/EFCoreSecondLevelCacheInterceptor#85]
# Summary of the issue
Is there a possibility to **not** cache a empty/null result of a Query?

## Environment

```
.NET (Core) SDK version: 
Microsoft.EntityFrameworkCore version: 3.1
EFCoreSecondLevelCacheInterceptor version: 2.0.1
Database: SQL Server
Cache provider: Cache Manager with Redis
```

## Example code/Steps to reproduce:

```
// May return null or a person
dataContext.Persons.Cachable().FirstOrDefault(x => x.Name == "Test")
```

## Output:
Either the empty/null result and the found person is cached.

**Comment by VahidN** [comment]
[Try V 2.4.0.](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor#skip-caching-of-some-of-the-queries-based-on-their-results)
