### ISSUE TITLE
Unable to update to v2.4.0

### ISSUE THREAD

**Issue by iamr8** [VahidN/EFCoreSecondLevelCacheInterceptor#87]
# Summary of the issue
As the reference to my [Project configuration](https://github.com/iamr8/R8/blob/b142f24a0e4633bdafcb3e635be32092d5f32963/src/R8.EntityFrameworkCore/R8.EntityFrameworkCore.csproj#L28-L38) , i'm not able to update `EFCoreSecondLevelCacheInterceptor` package in [my own nuget package](https://www.github.com/iamr8/r8) from `v2.3.0` to `v2.4.0`. Also github dependabot [confirms this issue](https://github.com/iamr8/R8/pull/9)

**Comment by VahidN** [comment]
Its failed log says:

> Install/reference `Microsoft.EntityFrameworkCore.Relational 5.0.2` directly to project `R8.EntityFrameworkCore` to resolve this issue.
> Install/reference `Microsoft.EntityFrameworkCore 5.0.2` directly to project `R8.EntityFrameworkCore.Test` to resolve this issue.
>

**Comment by iamr8** [comment]
So, why it is occurred for v2.4.0 version? I had no any issues with `EFCoreSecondLevelCacheInterceptor` previous versions !

I think the point of this issue is in [This line](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/fb8daabae4013e684c51626c27e866a92d0a4060/src/EFCoreSecondLevelCacheInterceptor/EFCoreSecondLevelCacheInterceptor.csproj#L90). The range you assigned to EFCore, is v3.1 up to v4.

EFCore v5 is being supported even in `netcoreapp3.1` ( as you see in my project ). But as [this reference](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/fb8daabae4013e684c51626c27e866a92d0a4060/src/EFCoreSecondLevelCacheInterceptor/EFCoreSecondLevelCacheInterceptor.csproj#L99) you assigned EF Core v5 only for `net5.0` and `netstandard2.1`. So when EF Core even supports in `netcoreapp3.1`, I think it's better to drop support for EFCore v3.1 and Use EF Core v5.0 for `netstandard2.1`, `netcoreapp3.1` and `net5.0`.

**Comment by iamr8** [comment]
Ummm.. Rasti 😆 

No need to drop support for EFCore v3.1. But It's better to extend EFCore supporting versions range to 3.1 up to 5.

**Comment by VahidN** [comment]
I'm not going to change anything, because it's discussed [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/52) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/50) and [here](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/56) before and some people want to stay on v3,1 and If I change it, they will be forced to use EF-Core 5x.

**Comment by iamr8** [comment]
So it's preferred to Create new nuget packages like : `EFCoreSecondLevelCacheInterceptor.EFCore5` and `EFCoreSecondLevelCacheInterceptor.EFCore3`.

In this case, Unable to update to newer versions of `EFCoreSecondLevelCacheInterceptor` for people like me!

**BTW, As you know!**

**Comment by VahidN** [comment]
Try V 2.4.1
