### ISSUE TITLE
InvalidCastException Int64 -> Int32 with SQLite

### ISSUE THREAD

**Issue by peterbucher** [VahidN/EFCoreSecondLevelCacheInterceptor#9]
# Summary of the issue
I am using **SQLite** with Entity Framework Core and getting an error if i want to cache data. The error only occous if i want to cache it globally or manually one by one.

## Environment

```
.NET Core SDK version: 3.1.2
Microsoft.EntityFrameworkCore version: 3.1.2
EFCoreSecondLevelCacheInterceptor version: 1.12
```

## Example code/Steps to reproduce:

```
as in your example.
```

## Output:

```
Exception message:
An unhandled exception occurred while processing the request.
InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetInt32(int ordinal)

Full Stack trace:
InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetInt32(int ordinal)
lambda_method(Closure , QueryContext , DbDataReader , ResultContext , int[] , ResultCoordinator )
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.MoveNext()
System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.ToList()
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
spots.Services.SpotsService.UpdateSpotViewModel(SpotsViewModel spotsViewModel, bool mySpots, int groupTab) in SpotsService.cs
+
            spotsViewModel.Spots = spots
```

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/c24fb32eaf7b7e00768746144e41f4de38650a78

**Comment by peterbucher** [comment]
Thanks, that problem is gone. But it has problems with double and decimal. I think it goes the same road?

````
InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.Decimal'.
EFCoreSecondLevelCacheInterceptor.EFTableRowsDataReader.GetDecimal(int ordinal)
lambda_method(Closure , QueryContext , DbDataReader , ResultContext , int[] , ResultCoordinator )
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.MoveNext()
System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.ToList()
````

**Comment by VahidN** [comment]
[I changed](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFTableRowsDataReader.cs#L203) `GetDecimal` method to support `string` types of SQLite.
- [Here is a test for it](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue9SQLiteInt32/Entities/Person.cs#L25)
- [Here EF Core translates it to an string and not a double](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/Tests/Issues/Issue9SQLiteInt32/Migrations/ApplicationDbContextModelSnapshot.cs#L40).
Where does this 'System.Double' come from? A ` Text` will become an `string` in EF Core internally.

**Comment by peterbucher** [comment]
Hi VahidN

I have this code:
````
[Column(TypeName = "numeric")]
public decimal? Latitude { get; set; }
````

Can that be supported somehow?

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/commit/d6dea6624b3838dcbaf101078285d98507f7b442

**Comment by peterbucher** [comment]
Hi VahidN

Great, it works! Thanks, looks very good :-)
